### ISSUE TITLE
2.5.1 erreur à l'installation d'occtax

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#1081]
je tombe sur une erreur essayant d'installer un nouveau GN en 2.5.1

on peut résoudre en changeant le fichier
```
File "contrib/occtax/backend/schemas.py", line 127, in ReleveSchema
    allow_none=current_app.config["OCCTAX"]["observers_txt"],
```

en 
```
    allow_none=current_app.config.get("OCCTAX", {}).get("observers_txt", {}),
```
mais je sais pas si c'est une vrai solution

l'erreur en question : 
checking file
...ok

checking manifest
...ok

Checking file conformity
      install_gn_module  OK
Traceback (most recent call last):
  File "/home/joel/info/app_gn/GeoNature/backend/geonature/core/command/create_gn_module.py", line 77, in install_gn_module
    .filter(TModules.module_code == module_code)
  File "/home/joel/info/app_gn/GeoNature/backend/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3473, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/info/app_gn/GeoNature/backend/venv/bin/geonature", line 3, in <module>
    geonature.core.command.main()
  File "/home/joel/info/app_gn/GeoNature/backend/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/joel/info/app_gn/GeoNature/backend/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/joel/info/app_gn/GeoNature/backend/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/joel/info/app_gn/GeoNature/backend/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/joel/info/app_gn/GeoNature/backend/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/joel/info/app_gn/GeoNature/backend/geonature/core/command/create_gn_module.py", line 92, in install_gn_module
    check_codefile_validity(module_path, module_code)
  File "/home/joel/info/app_gn/GeoNature/backend/geonature/utils/gn_module_import.py", line 234, in check_codefile_validity
    from backend.blueprint import blueprint
  File "contrib/occtax/backend/blueprint.py", line 44, in <module>
    from .schemas import OccurrenceSchema, ReleveCruvedSchema, ReleveSchema
  File "contrib/occtax/backend/schemas.py", line 108, in <module>
    class ReleveSchema(MA.SQLAlchemyAutoSchema):
  File "contrib/occtax/backend/schemas.py", line 127, in ReleveSchema
    allow_none=current_app.config["OCCTAX"]["observers_txt"],
KeyError: 'OCCTAX'
```

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.5.2
