### ISSUE TITLE
[SYNTHESE] Erreur 500 au téléchargement des statuts de protection

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#1203]
Rrproduit sur la prod DEPOBIO:
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 70, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/routes.py", line 563, in export_status
    q = synthese_query_class.filter_query_all_filters(info_role)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 307, in filter_query_all_filters
    self.filter_other_filters()
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 246, in filter_other_filters
    wkt = loads(str_wkt)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/shapely/wkt.py", line 10, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/shapely/geos.py", line 263, in read
    raise ReadingError("Could not create geometry because of errors "
shapely.geos.ReadingError: Could not create geometry because of errors while reading input.
[2020-12-24 16:05:15 +0100] [25523] [ERROR] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by camillemonchicourt** [comment]
OK peut-être du aux évolutions apportés avec les évolutions de l'export SIG désormais disponible en GPKG.

**Comment by lepontois** [comment]
Bonjour,

J'ai remarqué, sur mon GN local, que ce bug est toujours d'actualité à partir du moment où l'on applique un filtre géographique.

Sera-t-il corrigé sur la V2.6 ?

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.6.0
