### ISSUE TITLE
Occtax - Impossible de saisir avec une portée C=mes données

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1274]
L'un de mes utilisateurs avait des permissions C=mes données sur Occtax (et lire, exporter 3, delete 1 etc). 

Ca fonctionnait sans soucis il y a deux semaines, mais impossible pour lui de saisir aujourd'hui : "une erreur s'est produite" à l'enregistrement du relevé. Il a suffit de lui donner les droits Create=Les données de mon organisme pour que ça fonctionne de nouveau. 

A priori, lié à la 2.6, je n'ai rien fait d'autre que cette MAJ depuis les dernières saisies qui avaient marché :)

**Comment by bouttier** [comment]
Tu peux fournir les logs du serveur ?

**Comment by DonovanMaillard** [comment]
J'avais peut-être loupé la ligne la plus importante, tu as bien fait de m'y renvoyer. 

L'utilisateur/le groupe en lui même n'est pas acteur du JDD en question. A voir si ca vient de là, car le JDD lui est quand meme proposé à la saisie... 

Les logs : 
```
[2021-02-11 17:41:18 +0100] [15888] [ERROR] Error handling request /synthese?limit=100
Traceback (most recent call last):
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/outilsflavia/geonature/backend/wsgi.py", line 34, in __call__
    return self.app(environ, start_response)
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/outilsflavia/geonature/backend/geonature/core/gn_permissions/decorators.py", line 74, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/outilsflavia/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 23, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/outilsflavia/geonature/backend/geonature/core/gn_synthese/routes.py", line 211, in get_synthese
    feature = d.get_geofeature(columns=columns)
AttributeError: Could not locate column in row for column 'get_geofeature'
[2021-02-11 17:42:09 +0100] [19306] [ERROR] ('User 15 has no right in dataset 5', 403)
```

**Comment by bouttier** [comment]
Dans tous les cas, on devrait avoir une 403 plutôt qu’une 500, et on ne devrait pas être amené à pouvoir faire la saisie si on n’a pas les permissions. À corriger donc.

**Comment by TheoLechemia** [comment]
Il y a deux erreurs dans les logs. La 1ere est lié à la synthese ? 
La seconde est bien celle qui concerne Occtax: `[2021-02-11 17:42:09 +0100] [19306] [ERROR] ('User 15 has no right in dataset 5', 403)` et c'est bien une erreur 403 qui est levé.
Le problème est expliqué ici: https://github.com/PnX-SI/GeoNature/issues/552
En fait la récupération des JDD est une route générique à tous GN et le CRUVED utilisé est le "R" de GeoNature. Donc ton utilisateur a un R = 2 ou 3 sur GN, mais un C = 1 dans OCCTAX. On lui remonte tous les JDD car il peut les "voir", mais pas saisir dedans. 
Il faudrait trouvé une solution au ticket mentionné pour résoudre le soucis. En attendant je peux mettre un message plus compréhensible (et tu peux passer le C de Occtax au même niveau que ton R GeoNature)
Et l'erreur ne date pas de la 2.6.0

**Comment by DonovanMaillard** [comment]
Ok merci pour ton retour ! 

Alors l'utilisateur a du saisir dans un autre JDD la dernière fois, mais ca me semble bizarre, c'est notre JDD "opportuniste" qui lui a été refusé et il l'a déjà utilisé. Peut etre un changement des acteurs ou autre au niveau des mtd de notre coté, j'ai corrigé dans tous les cas... dans tous les cas, ca veut dire qu'il faut C=R et des acteurs qui sont bien calibrés si on a un utilisateur avec ses propres données seulement. Merci !

**Comment by camillemonchicourt** [comment]
Ça pourrait être ce même soucis qui fait que l'on récupère plus correctement les JDD avec Occtax-mobile branché sur notre GN 2.6.2.

**Comment by camillemonchicourt** [comment]
A partir de la 2.9.0, la liste des JDD proposée à l'utilisateur lors de la saisie dans un module est basé sur le C du CRUVED de l'utilisateur (ou du C du CRUVED sur GeoNature si l'utilisateur n'a pas de permissions définies sur le module).

On peut donc clore ce ticket @DonovanMaillard ?
