### ISSUE TITLE
[2.7] - OCCTAX : Erreur sur le cruved

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1413]
Bonjour, 

Pour un utilisateur avec un droit de création à 2 (mon organisme) dans Occtax, nous avons un problème nouveau sur notre instance. 

Jusqu'en 2.6.2 l'utilisateur pouvait saisir dans les jeux dont notre organisme est acteur, désormais il ne peut plus, il a une erreur "object object" et c'est tout. Coté logs, nous avons ce qui suit. Réglé temporairement avec la portée Create=3 dans occtax, mais pas pertinent à terme.

```
[2021-07-04 18:18:54 +0200] [18556] [ERROR] Exception on /occtax/only/releve [POST]
Traceback (most recent call last):
  File "/home/<monuser>/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/<monuser>/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/<monuser>/geonature/backend/geonature/core/gn_permissions/decorators.py", line 70, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/<monuser>/geonature/external_modules/occtax/backend/blueprint.py", line 490, in createReleve
    .dump(releveHandler(request=request, releve=releve, info_role=info_role))
  File "/home/<monuser>/geonature/external_modules/occtax/backend/blueprint.py", line 430, in releveHandler
    403,
pypnusershub.db.tools.InsufficientRightsError: ('User 15 has no right in dataset None', 403)
```

**Comment by jbrieuclp** [comment]
La même ici, j'ai cru que c'était en lien avec ça https://github.com/PnX-SI/GeoNature/issues/1365, mais en fait non.
Je n'ai pas encore cherché l'origine.

**Comment by TheoLechemia** [comment]
J'ai trouvé, je suis dessus

**Comment by jbrieuclp** [comment]
et moi j'ai complété mon post :D

**Comment by TheoLechemia** [comment]
https://github.com/PnX-SI/GeoNature/commit/243dff47cda7bfc15d51a21885ba69af6082c6f9
Le cruved était checké avant que le relevé soit chargé

**Comment by TheoLechemia** [comment]
J'ai réécris des tests sur la route` /only/releve`. Il faudrait ré augmenter la couverture de test sur occtax car avec le passage sur les routes séparées, on a souvent des regressions !
Avis aux amateurs ...
