### ISSUE TITLE
[2.7.5] Métadonnées - téléchargement des fiches PDF impossible

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1449]
Bonjour,

Sur GeoNature 2.7.4, la génération des PDF des fiches des JDD et CA se fait sans problème. Mais cela ne fonctionne plus avec la version 2.7.5 (debian 10), que ce soit après une mise à jour de la 2.7.4 vers 2.7.5 ou une installation directe de 2.7.5 sur un serveur vierge.

Au clic sur le bouton de téléchargement  je reçois un "internal serveur error", et dans les logs de GeoNature voilà ce que je trouve : 

```
Exception on /meta/dataset/export_pdf/179 [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    return handler(e)
  File "/home/geonatureadmin/geonature/backend/geonature/core/errors/routes.py", line 82, in handle_exception
    raise e
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 70, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_meta/routes.py", line 631, in get_export_pdf_dataset
    pdf_file = fm.generate_pdf("dataset_template_pdf.html", dataset, filename)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/filemanager.py", line 89, in generate_pdf
    html_file.write_pdf(file_abs_path)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/__init__.py", line 183, in write_pdf
    counter_style=counter_style, image_cache=image_cache)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/__init__.py", line 136, in render
    optimize_size, font_config, counter_style, image_cache)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/document.py", line 885, in _render
    [Page(page_box) for page_box in page_boxes],
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/document.py", line 885, in <listcomp>
    [Page(page_box) for page_box in page_boxes],
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/__init__.py", line 124, in layout_document
    pages = list(make_all_pages(context, root_box, html, pages))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/pages.py", line 802, in make_all_pages
    page, resume_at = remake_page(i, context, root_box, html)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/pages.py", line 741, in remake_page
    page_number, page_state)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/pages.py", line 552, in make_page
    positioned_boxes, adjoining_margins, discard=False)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins, discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins, discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 520, in block_container_layout
    absolute_boxes, fixed_boxes, adjoining_margins, discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins, discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins, discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 520, in block_container_layout
    absolute_boxes, fixed_boxes, adjoining_margins, discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 60, in block_level_layout
    page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins, discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 75, in block_level_layout_switch
    discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 128, in block_box_layout
    absolute_boxes, fixed_boxes, adjoining_margins, discard)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/blocks.py", line 379, in block_container_layout
    for i, (line, resume_at) in enumerate(lines_iterator):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/inlines.py", line 50, in iter_line_boxes
    absolute_boxes, fixed_boxes, first_letter_style)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/inlines.py", line 150, in get_next_linebox
    context, linebox, skip_stack=skip_stack, first_line=True)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 202, in inline_min_content_width
    widths = [next(widths)]
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 327, in inline_line_widths
    lines = [0, max_content_width(context, child), 0]
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 75, in max_content_width
    return block_max_content_width(context, box, outer)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 185, in block_max_content_width
    return _block_content_width(context, box, max_content_width, outer)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 98, in _block_content_width
    function(context, child, outer=True) for child in box.children
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 99, in <listcomp>
    if not child.is_absolutely_positioned()]
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 75, in max_content_width
    return block_max_content_width(context, box, outer)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 185, in block_max_content_width
    return _block_content_width(context, box, max_content_width, outer)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 98, in _block_content_width
    function(context, child, outer=True) for child in box.children
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 99, in <listcomp>
    if not child.is_absolutely_positioned()]
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 80, in max_content_width
    context, box, outer, is_line_start=True)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 212, in inline_max_content_width
    inline_line_widths(context, box, outer, is_line_start, minimum=False))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 282, in inline_line_widths
    lines = list(lines)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/layout/preferred.py", line 311, in inline_line_widths
    minimum=True))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/text/line_break.py", line 342, in split_first_line
    text, style, context, original_max_width, justification_spacing)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/text/line_break.py", line 278, in create_layout
    context, style['font_size'], style, justification_spacing, max_width)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/text/line_break.py", line 84, in __init__
    self.setup(context, font_size, style)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/weasyprint/text/line_break.py", line 100, in setup
    pango.pango_context_set_round_glyph_positions(pango_context, False)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'pango_context_set_round_glyph_positions' not found in library 'libpango-1.0.so.0': /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: pango_context_set_round_glyph_positions
```

D'autres utilisateurs ont le même souci, ou cela vient d'une erreur commise de mon côté ?

Vu ce que je comprends de discussions sur différents forums, c'est peut-être bien libpango qui ne serait pas dans la bonne version. Mais je préfère demander une confirmation plutôt que d'essayer bêtement des suites de commandes que je ne suis pas sûr de comprendre ^^

Merci d'avance !

**Comment by bouttier** [comment]
Bonjour,
Je suspect le problème causé par la sortie de weasyprint version 53 le 31 août dernier requérant la version 1.44 minimum de Pango alors que Debian 10 fournis la version 1.42.4.
Pouvez-vous essayer d’installer weasyprint version inférieur à 52 avec : `pip install "weasyprint<53"`

**Comment by Splendens** [comment]
Bingo, c'était bien ça : les PDF des fiches de métadonnées sont de nouveau générés . Merci beaucoup !

**Comment by bouttier** [comment]
Correction : https://github.com/PnX-SI/GeoNature/commit/af169ae3dd894055501779282c133b095ad1eff3
