### ISSUE TITLE
[Validation] Erreur sur une validation massive

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1485]
Bonjour,

Un utilisateur et moi-même essayons de valider plusieurs occurrences d'un seul coup en sélectionnant environ 700 à 1000 entités.
Or, un message d'erreur 414 s'affiche : 
![image](https://user-images.githubusercontent.com/66769358/136205555-d229e22d-bd60-4a11-971c-4c271fe161f6.png)

En premier lieu, j'ai donc modifié (même si déconseillé) la valeur de `LimitRequestLine` dans le fichier de configuration d'Apache (https://stackoverflow.com/a/2891598)
Mais cela n'a résolu qu'une partie du problème, je ne peux toujours pas validation une grande quantité d’occurrences. Mais cette fois-ci, le message est plus court : 
![image](https://user-images.githubusercontent.com/66769358/136205837-65b7004b-dcd9-4520-a7a5-28f389e71ef1.png)

J'ai vérifié sur le logs de GeoNature et voici l'erreur rapportée avant la limit modifiée et après : 

**Avant**

    [2021-10-06 14:51:17 +0200] [30135] [ERROR] Validation : colonne VSyntheseValidation.id_nomenclature_valid_status inexistante
    Validation : colonne VSyntheseValidation.id_nomenclature_valid_status inexistante

**Après valeur limit modifiée**

    [2021-10-06 14:51:35 +0200] [30169] [ERROR] Validation : colonne VSyntheseValidation.id_nomenclature_valid_status inexistante
    /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/sql/base.py:302: SAWarning: Can't validate argument 'dialect_options'; can't locate any SQLAlchemy dialect named 'dialect'
      % (k, dialect_name)
    Validation : colonne VSyntheseValidation.id_nomenclature_valid_status inexistante

J'ai vérifié et j'ai bien la colonne `id_nomenclature_valid_status` dans la table t_validations...
Avez-vous une idée d'où peut venir ce soucis ?

Merci d'avance !

**Comment by DonovanMaillard** [comment]
VSyntheseValidation n'est probablement la table t_validations, mais une vue v_synthese_validation. A voir du coté de cette vue en priorité

**Comment by maximetoma** [comment]
La colonne est également présente dans le vue `v_synthese_validation_for_webapp`

**Comment by maximetoma** [comment]
Bonjour,

Nouveau problème sur la validation, depuis la 2.8, je me rends compte que je ne peux plus valider les occurrences. Le log m'affiche cette erreur, est-ce que vous avez une idée (côté WEB j'ai une erreur 500) ? Merci :)

[2021-12-21 15:30:33 +0100] [12492] [ERROR] Validation : colonne VSyntheseValidation.id_nomenclature_valid_status inexistante
Validation : colonne VSyntheseValidation.id_nomenclature_valid_status inexistante
[2021-12-21 15:30:51 +0100] [12492] [ERROR] Validation : colonne VSyntheseValidation.id_nomenclature_valid_status inexistante
Exception on /validation/889622,889632 [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 70, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/contrib/gn_module_validation/backend/gn_module_validation/blueprint.py", line 205, in post_status
    session=DB.session
TypeError: cannot unpack non-iterable TValidations object
[2021-12-21 15:31:05 +0100] [12492] [ERROR] Exception on /validation/889622,889632 [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 70, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/contrib/gn_module_validation/backend/gn_module_validation/blueprint.py", line 205, in post_status
    session=DB.session
TypeError: cannot unpack non-iterable TValidations object

**Comment by camillemonchicourt** [comment]
Oui pas mal de soucis du module Validation dans la 2.8 qui sont corrigés dans la develop en cours de finalisation pour la release 2.9.

**Comment by maximetoma** [comment]
Okay dak, pas de soucis merci de l'info ;)

**Comment by JeromeMaruejouls** [comment]
Bonjour à tous.
J'ai moi aussi ces messages récurrents dans mes logs : 

`Validation : colonne VSyntheseValidation.id_nomenclature_valid_status inexistante`

Mais aucun problème apparent lors de la validation. Tout est normal.
Est ce que la source des ces remontées de log a été identifiée ? Je suis encore en 2.7.5 et je ne sais pas si le problème persiste en 2.9. Merci

**Comment by camillemonchicourt** [comment]
Oui merci de tester en version 2.9 et de nous faire un retour car on ne peut passer du temps sur des tests et améliorations sur des vieilles versions qui sont potentiellement améliorés dans les dernières versions.

**Comment by JeromeMaruejouls** [comment]
Merci, c'est prévu :)
