### ISSUE TITLE
Migration 2.7.5 vers 2.8.1 : connexion à GN impossible, et pas d'accès à Taxhub

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1516]
Bonjour,

Je suis en train de tester la migration vers GN 2.8.1 : 
 - j'ai fais une nouvelle installation de GN 2.7.5, TH 1.8.1, UH2.13 sur debian 10
 - avec les modules import 1.1.4, exports 1.2.5 et monitoring 0.2.7
 - les applis fonctionnaient très bien, et accessibles en HTTPS sur des URL avec sous-domaine (taxhub.mondomaine.fr, usershub.mondomaine.fr et geonature.mondomaine.fr)

J'ai suivi les notes de mises à jour des 3 applis :
- j'ai pris directement les versions GN 2.8.1, TH 1.9.1 et UH 2.2.1
- maj de taxhub et de usershub sans l'étape concernant Alembic
- le fichier de config de Taxhub est bien dans le dossier apptax
- puis maj de geonature avec la partie sur Alembic

Les seules "erreurs" que j'ai eu lors de la migration sont plusieurs : `Configuration du module non accéssible (installation en cours)`

---------------
**Usershub**

Usershub ne fonctionnait pas, car dans le fichier de config, le `URL_APPLICATION` a été remplacé lors de la migration. J'ai remis la bonne URL et lancé `sudo systemctl restart usershub` => usershub fonctionne, et je peux m'y connecter.

---------------
**Geonature**

La page de connexion de GeoNature est accessible, mais impossible de se connecter.

Dans /var/log/geonature.log :
```
[2021-11-03 16:49:54 +0000] [1490] [ERROR] Error handling request /gn_commons/modules
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 167, in handle_request
    listener.getsockname(), self.cfg)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 202, in create
    path_info = path_info.split(script_name, 1)[1]
IndexError: list index out of range
[2021-11-03 16:49:58 +0000] [1487] [ERROR] Error handling request /auth/login
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 167, in handle_request
    listener.getsockname(), self.cfg)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 202, in create
    path_info = path_info.split(script_name, 1)[1]
IndexError: list index out of range
[2021-11-03 16:50:01 +0000] [1490] [ERROR] Error handling request /auth/login
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 167, in handle_request
    listener.getsockname(), self.cfg)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 202, in create
    path_info = path_info.split(script_name, 1)[1]
IndexError: list index out of range
[2021-11-03 16:50:07 +0000] [1489] [ERROR] Error handling request /auth/login
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 167, in handle_request
    listener.getsockname(), self.cfg)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 202, in create
    path_info = path_info.split(script_name, 1)[1]
IndexError: list index out of range
```

Dans la console, j'ai une erreur 500 sur le `https<monurl>/api/auth/login`

Jusque là, les seules fois où j'ai été confrontée à ce type d'erreur, le problème venait de UsersHub qui fonctionnait pas. Du coup, je n'ai pas trop d'idées sur l'origine du problème.

-------------
**Taxhub**

J'arrive sur une page "cette page de fonctionne pas",  avec un `ERR_TOO_MANY_REDIRECTS`.

Dans  /var/log/taxhub.log :  
```
[2021-11-03 16:44:10 +0000] [30777] [INFO] Worker exiting (pid: 30777)
[2021-11-03 16:44:10 +0000] [30780] [INFO] Worker exiting (pid: 30780)
[2021-11-03 16:44:10 +0000] [30774] [INFO] Handling signal: term
[2021-11-03 16:44:10 +0000] [30779] [INFO] Worker exiting (pid: 30779)
[2021-11-03 16:44:10 +0000] [30778] [INFO] Worker exiting (pid: 30778)
[2021-11-03 16:44:10 +0000] [30774] [INFO] Shutting down: Master
[2021-11-03 16:44:10 +0000] [1453] [INFO] Starting gunicorn 20.0.4
[2021-11-03 16:44:10 +0000] [1453] [INFO] Listening at: http://127.0.0.1:5000 (1453)
[2021-11-03 16:44:10 +0000] [1453] [INFO] Using worker: sync
[2021-11-03 16:44:10 +0000] [1456] [INFO] Booting worker with pid: 1456
[2021-11-03 16:44:10 +0000] [1457] [INFO] Booting worker with pid: 1457
[2021-11-03 16:44:10 +0000] [1458] [INFO] Booting worker with pid: 1458
[2021-11-03 16:44:10 +0000] [1459] [INFO] Booting worker with pid: 1459
```

Je n'ai rien changé à la conf apache, qui fonctionnait sans problème avant la tentative de migration : 

```
<VirtualHost *:80>
            ServerName taxhub.chezmoi.fr

            <Location />
                    ProxyPass http://127.0.0.1:5000/
                    ProxyPassReverse http://127.0.0.1:5000/
            </Location>
    RewriteEngine on
RewriteCond %{SERVER_NAME} =taxhub.chezmoi.fr
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

Cela pourrait quand même provenir de la conf Apache ?

-----------
Merci d'avance si quelqu'un peut m'aider !

**Comment by bouttier** [comment]
Bonjour,

Pour GeoNature, l’erreur provient d’une inadéquation entre la configuration apache et la configuration de GeoNature (le paramètre ``URL_APPLICATION``). Quelle est la valeur de ``URL_APPLICATION`` et quelle est la configuration apache pour GeoNature ?

Pour TaxHub, la configuration apache du vhost redirige l’utilisateur vers la version HTTPS. Quelle est la configuration apache du vhost taxhub HTTPS afin de vérifier sa validité ?

**Comment by Splendens** [comment]
Dans la conf apache de GeoNature, (fichiers  `/etc/apache2/sites-available/geonature-le-ssl.conf` et `/etc/apache2/sites-available/geonature.conf`), la partie proxy était mal écrite, il manquait les /api :
```
            <Location /api>
                    ProxyPass http://127.0.0.1:8000
                    ProxyPassReverse  http://127.0.0.1:8000
            </Location>
```
Corrigés en : 
```
            <Location /api>
                    ProxyPass http://127.0.0.1:8000/api
                    ProxyPassReverse  http://127.0.0.1:8000/api
            </Location>
```

Avec cette correction c'est bon, je peux bien me connecter à GeoNature !

---------------

Pour Taxhub, voilà les config apache : 


 **/etc/apache2/sites-available/taxhub.conf**
 ```
   <VirtualHost *:80>
            ServerName taxhub.chezmoi.fr

            <Location />
                    ProxyPass http://127.0.0.1:5000/
                    ProxyPassReverse http://127.0.0.1:5000/
            </Location>
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =taxhub.chezmoi.fr
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

 **/etc/apache2/sites-available/taxhub-le-ssl.conf**
```
<IfModule mod_ssl.c>
    <VirtualHost *:443>
            ServerName taxhub.chezmoi.fr

            <Location />
                    ProxyPass http://127.0.0.1:5000/
                    ProxyPassReverse http://127.0.0.1:5000/
            </Location>

           SSLCertificateFile /etc/letsencrypt/live/taxhub.chezmoi.fr/fullchain.pem
           SSLCertificateKeyFile /etc/letsencrypt/live/taxhub.chezmoi.fr/privkey.p$
           Include /etc/letsencrypt/options-ssl-apache.conf
      </VirtualHost>
</IfModule>
```

**Comment by bouttier** [comment]
La configuration Apache pour TaxHub me semble correcte. Pouvez-vous essayer de vider le cache du navigateur et de re-essayer d’accéder à TaxHub ?

Juste pour être sûr, le paramètre ``APPLICATION_ROOT`` est-il définie dans le fichier de configuration de TaxHub ``apptax/config.py`` ? Pour le cas présent où TaxHub est servie sur un sous-domaine, il ne devrait pas être définie, ou être égal à ``/``.

**Comment by bouttier** [comment]
Quelles sont la ou les redirections rencontrées ? (donnée par exemple dans la console réseau du navigateur)

**Comment by Splendens** [comment]
Dans la partie "network", lors du chargement/rechargement de la page, j'ai 2 lignes qui arrivent en boucle :
```
Name : taxhub.chezmoi.fr  Status : 308  Type : document/Redirect  Initiator : taxhub.chezmoi.fr/
Name : taxhub.chezmoi.fr  Status : 301  Type : document/Redirect  Initiator : taxhub.chezmoi.fr/
```

(Merci beaucoup de prendre du temps pour m'aider !)

**Comment by bouttier** [comment]
Je ne comprend pas trop pourquoi il y a ces 2 redirections … es-tu sûr de ne pas avoir d’autres fichiers de configuration apache activé pouvant interférer ?

**Comment by Splendens** [comment]
C'est bon ça fonctionne !

J'ai modifié le paramètre application_root en `APPLICATION_ROOT = ''`, relancer le service taxhub, et maintenant c'est bon.
Pour le  test, j'ai réessayé avec `APPLICATION_ROOT = '/'`, et j'ai de nouveau les erreurs de redirection.

> Dans le fichier apptax/config.py, je n'avais rien défini pour APPLICATION_ROOT . J'ai l'ai changé en APPLICATION_ROOT = '/' mais pas de changement...

Dans ce message j'aurai dû préciser que quand je n'avais rien défini, c'est que j'avais commenté la ligne (il n'y avait donc pas le paramètre)...

Mystère résolu ! 
Merci beaucoup de m'avoir aider !

**Comment by bouttier** [comment]
Hum, il ne devrait pas y avoir besoin de définir ``APPLICATION_ROOT = ''``; cela devrait marcher avec ``APPLICATION_ROOT = '/'`` (valeur par défaut lorsque le paramètre n’est pas définie. Mais je pense savoir d’où vient le soucis : il doit provenir de ``ProxyPass http://127.0.0.1:5000/`` au lieu de ``ProxyPass http://127.0.0.1:5000`` (sans le ``/`` finale).
Peux-tu essayer de commenter ``APPLICATION_ROOT`` dans ta config TaxHub (et redémarrer taxhub) et enlever les ``/`` finaux à ``ProxyPass`` et ``ProxyPassReverse`` dans la conf du vhost 443 (et reloader apache) et vérifier que cela fonctionne toujours ?

**Comment by Splendens** [comment]
En faisant ça, j'ai de nouveau les erreurs de redirection.
Ensuite, si je décommente le `APPLICATION_ROOT = ''` (et je redémarre taxhub), je n'ai pas d'erreur de redirection, mais la page de taxhub reste vide avec plein d'erreurs de proxy dans la console : `Failed to load resource: the server responded with a status of 502 (Proxy Error)`

**Comment by bouttier** [comment]
Ok merci beaucoup pour le retour, j’essayerai d’investiguer un peu plus pour mieux comprendre la validité des paramètres.

**Comment by camillemonchicourt** [comment]
Problème résolu il me semble
