### ISSUE TITLE
Erreur migration de GN 2.7.5 à 2.8.1

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/GeoNature#1522]
Lors du lancement de la commande migration.sh pour mettre à jour GeoNature de 2.7.5 à 2.8.1 en lisant les consignes de 2.8.0, nous avons en dernière ligne sur de la commande ./install/migration/migration.sh
 : ModuleNotFoundError: No Module named 'wtforms.compat', ce qui rend impossible la fin de la migration. 

En amont, nous avions déja mis à jour  UsersHub en version 2.2.1 et TaxHub en version 1.9.1  SANS sauter leur étape de passage à Alembic. TaxHub fonctionne et UsersHub ne fonctionne pas actuellement, cependant nous avons vu que c'est du à la non mise à jour de GeoNature [#145](https://github.com/PnX-SI/UsersHub/issues/145). Nous avons utiliser pour TH et UH le fichier de conf-available.

**Comment by bouttier** [comment]
Bonjour,
Quels sont les modules que vous avez d’installés ? (= liste des liens dans``external_modules``)

**Comment by Chrispnv** [comment]
Actuellement il n'y en a aucun sur GN 2.8.1.  

Nous avions sur la version d'avant (GN 2.7.5): dashboard en version 1.0.0, import en v1.1.2, exports en v1.2.4, monitorings v 0.2.6, occhab v1.1.0, occtax v1.1.0, validation v1.1.0.

**Comment by bouttier** [comment]
Quelle est la ligne précisément de ``migration.sh`` qui lève cette l’erreur ? N’y a-t-il pas un peu plus de contexte à l’erreur ?

**Comment by Chrispnv** [comment]
Bonjour, 
Nous avons donc séparer en plusieurs parties le fichier `migration.sh`. Actuellement nous avons réussi à avoir de nouveau les mêmes `external_modules` que nous avions dans le version GN 2.7.5. 

Le dernier fichier recoupé de `migration.sh` qui lève l'erreur est sur le partie de l'installation `python3 -m venv venv` 

Le dernier message avant l'erreur est ce dernier:  
`Installing` collected packages: geonature
  Running setup.py develop for geonature
Successfully installed `geonature-2.8.1`

Puis nous avons ensuite ce message qui arrête la migration:
`Traceback (most recent call last):
  File "/home/geonatadmin/geonature/backend/venv/bin/geonature", line 11, in <module>
    load_entry_point('geonature', 'console_scripts', 'geonature')()
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 381, in load_app
    app = call_factory(self, self.create_app)
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/home/geonatadmin/geonature/backend/geonature/app.py", line 139, in create_app
    blueprint = getattr(import_module(module_name), blueprint_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/geonatadmin/geonature/backend/geonature/core/gn_permissions/backoffice/views.py", line 18, in <module>
    from geonature.core.gn_permissions.backoffice.forms import (
  File "/home/geonatadmin/geonature/backend/geonature/core/gn_permissions/backoffice/forms.py", line 18, in <module>
    from wtforms_sqlalchemy.fields import QuerySelectField
  File "/home/geonatadmin/geonature/backend/venv/lib/python3.7/site-packages/wtforms_sqlalchemy/fields.py", line 7, in <module>
    from wtforms.compat import string_types
ModuleNotFoundError: No module named 'wtforms.compat'`

Nous avons essayé d'installer la libraire wtforms mais cela n'a rien changer aux messages d'erreur.

**Comment by antoinececchimnhn** [comment]
Il y a eu une release hier du package wtforms qui est une dépendance de 
WTForms_SQLAlchemy.

Une solution pour continuer à pouvoir utiliser le module compat est de 
forcer la version de wtforms.

Dans le venv:

     pip uninstall WTForms

     pip install WTForms==2.3.3

Le 09/11/2021 à 09:08, CHILLET Christophe a écrit :

**Comment by Chrispnv** [comment]
Bonjour, 
Merci pour votre retour, nous avons effectué cette commande dans le venv, cependant nous avons encore le même message d'erreur avec une ligne en plus : 

`ModuleNotFoundError: No module named 'wtforms.compat'
Failed to restart geonature.service: Unit geonature.service not found.
`

**Comment by Chrispnv** [comment]
Afin d'effectuer le uninstall WTForms 3.0.0 et l'install de WTForms==2.3.3, il faut bien activer le venv, sinon la librairie est installée dans /home/[usercourant]/.local/lib/python/3.7/site-package
Donc nous avons bien la librairie WTForms 2.3.3 dans /home/[usercourant]/geonature/backend/venv/lib/python/3.7/site-package

Une fois cela fait, nous avons relancé le script de migration de Geonature (migration.sh)
dans migration.sh, il y a la commande pip install --upgrade "pip>=19.3"  # https://www.python.org/dev/peps/pep-0440/#direct-references qui installe la dernière version de pip et de l'environnement Python 3 utile pour Geonature dans /home/[usercourant]/geonature/backend/venv/lib/python/3.7/site-package. Donc cela supprime et remplace la librairie WTForms 2.3.3 par la WTForms 3.0.0
On a essayé de commenter cette commande pip install --upgrade "pip>=19.3" dans migration.sh, mais cela crée pleins d'erreurs dans l'exécution du script et rien ne fonctionne

Donc c'est le serpent qui se mord la queue. On ne sait pas imposer la librairie WTForms 2.3.3 lors de l'exécution du script migration.sh puisque l'ensemble des librairies dans /home/[usercourant]/geonature/backend/venv/lib/python/3.7/site-package sont mises à jour lors de l'exécution de migration.sh

Est ce que quelqu'un a une idée ?

Merci d'avance.

**Comment by TheoLechemia** [comment]
Salut,
En fait ce n'est pas le "upgrade pip" qui supprime WTForm, mais la commande d'après ( `pip install -r requirements.txt`) qui installe WTForm via une autre dépendances dans laquelle la version n'est pas fixé (ou fixée à une version inferieure à celle qui tu veux.)
Tu peux éditer le fichier `backend/requirements-commons.txt` et y ajouter cette ligne pour forcer la version : 
`WTForms==2.3.3`

**Comment by Chrispnv** [comment]
Salut,
@TheoLechemia merci pour cette petite ligne à ajouter !
N'étant pas à l'aise sur Github on n'avait pas récupérer la correction faite par rapport à cette ligne à rajouter. On l'a vu une fois que tu nous l'as dit.

Ca y est notre Geonature 2.8.1 est installé et fonctionnel, ainsi que Taxhub en 1.9.1 et Usershub 2.2.1.
On a aussi installé des modules. 
On va se finaliser avec Geonature mobile pour Android 11.

Merci à tous les contributeurs pour votre aide pour l'installation et la configuration de notre environnement Geonature !

**Comment by camillemonchicourt** [comment]
A noter aussi que la fixation de la version de WTForms a été faire dans al branche ``develop``, mais aussi dans la branche ``master`` et intégrée entre temps dans la version 2.8.1, sans faire une nouvelle release : https://github.com/PnX-SI/GeoNature/commit/52224ffe510a69205dc4fd9066b009aca048343e
