### ISSUE TITLE
[2.8.1] Création de compte impossible

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1527]
Bonjour, 

Une info et un soucis :) . La route **http://geonature.mondomaine.fr/api/users/inscription** renvoie une erreur 404 tant qu'on a pas stoppé/relancé GeoNature après l'update_configuration à priori.

Sinon il reste un soucis avec l'ID_APPLICATION_GEONATURE . La demande de création de compte arrive bien, mais le lien envoyé par mail pour valider la création du compte n'est pas fonctionnel et renvoie l'erreur suivante : 

[2021-11-20 18:48:30 +0000] [127204] [ERROR] Exception on /users/confirmation [GET]
Traceback (most recent call last):
  File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    return handler(e)
  File "/home/loparvi-gnadmin/geonature/backend/geonature/core/errors.py", line 82, in handle_exception
    raise e
  File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/loparvi-gnadmin/geonature/backend/geonature/core/users/routes.py", line 339, in confirmation
    data = {"token": token, "id_application": config["ID_APPLICATION_GEONATURE"]}
  File "/usr/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'ID_APPLICATION_GEONATURE'

Merci !

**Comment by DonovanMaillard** [comment]
au temps pour moi, j'ai relancé (une seconde fois) l'update_configuration, puis stoppé/lancé GeoNature, ça a réglé le soucis!

**Comment by DonovanMaillard** [comment]
après avoir creusé un peu, 

- le paramètre ID_APPLICATION_GEONATURE ne semble pas récupéré correctement depuis la conf  (L339 de backend/geonature/core/routes.py). Si je mets mon id en dur sur cette ligne le lien fonctionne bien, sinon on a l'erreur ci-dessus et le navigateur renvoie une erreur 500. 


- En faisant la validation par usershub et non pas par le mail, ça active bien l'utilisateur mais avec une erreur qui ressort : 

`File "/home/loparvi-gnadmin/geonature/backend/geonature/core/users/routes.py", line 355, in after_confirmation
    after_confirmation_fn = function_dict.get(type_action, None)`

**Comment by bouttier** [comment]
Le paramètre ``ID_APPLICATION_GEONATURE`` étant désormais récupéré dynamiquement et non plus à partir de la config, il faut le récupérer depuis ``curent_app.config`` au lieu de l’objet config importé.
