### ISSUE TITLE
[2.8.1] - Erreur 500 à la validation des données

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1529]
**Version**
2.8.1 - installation neuve

**Description du bug**
Sur une installation neuve ne comportant qu'une ou deux données lors de mes différents tests, il m'est impossible d'attribuer un statut de validation à une donnée. Le navigateur renvoie une erreur 500. 

Les logs de GeoNature renvoient l'erreur suivante : 
`[2021-11-20 21:12:41 +0000] [129497] [ERROR] Exception on /validation/1 [POST]
Traceback (most recent call last):
  File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/loparvi-gnadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 70, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/loparvi-gnadmin/geonature/contrib/gn_module_validation/backend/gn_module_validation/blueprint.py", line 203, in post_status
    validation, errors = validationSchema.load(
TypeError: cannot unpack non-iterable TValidations object`

**Comment by bouttier** [comment]
Lié au passage à Marshmallow 3
Corrigé : 3bdef1b7bd485b68db873cbfa852a550bad2793c

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.9.0
