### ISSUE TITLE
Export PDF d'un jeu de données impossible (2.8.1)

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1544]
**Version**
2.8.1

**Description du bug**
Impossible de télécharger une fiche PDF de jeu de données depuis le module métadonnées, sur une installation récente : que le jeu de données comporte ou non une occurrence.

**Comportement attendue**
Export du PDF

**Comment reproduire**
Exporter un pdf de jeu de données depuis le module MTD

**Logs**

> [2021-11-29 00:39:13 +0000] [243694] [ERROR] Exception on /meta/dataset/export_pdf/2 [GET]
> Traceback (most recent call last):
>   File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
>     return handler(e)
>   File "/home/loparvi-gnadmin/geonature/backend/geonature/core/errors.py", line 82, in handle_exception
>     raise e
>   File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/loparvi-gnadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/loparvi-gnadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 70, in __check_cruved_scope
>     return fn(*args, **kwargs)
>   File "/home/loparvi-gnadmin/geonature/backend/geonature/core/gn_meta/routes.py", line 589, in get_export_pdf_dataset
>     dataset = json.loads((datasetSchema.dumps(dataset)).data)
> AttributeError: 'str' object has no attribute 'data'
> 
> 
>

**Comment by DonovanMaillard** [comment]
L'export pour les cadres d'acquisition semble bien fonctionner en revanche.
