### ISSUE TITLE
IdleInTransactionSessionTimeout à l'installation

### ISSUE THREAD

**Issue by remche** [PnX-SI/GeoNature#1752]
**Version**
2.9.2

**Description du bug**
À l'installation, l'étape `Refresh DEM spatial index` échoue avec un IdleInTransactionSessionTimeout, malgré l'augmentation du timeout à 20 minutes.

Notez que PostgreSQL (11) tourne sur un autre machine, le script `02_create_db.sh`a été modifié en conséquence.

**Logs**

```
INFO  [alembic.runtime.migration] Running upgrade  -> 1715cf31a75d, Insert default French DEM (IGN 250m BD alti)
Processing 1/1: /tmp/tmp2aqec3v3/BDALTIV2_250M_FXX_0098_7150_MNT_LAMB93_IGN69.asc
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
INFO  [alembic.runtime.migration] Refresh DEM spatial index…
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.IdleInTransactionSessionTimeout: terminating connection due to idle-in-transaction timeout
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
[...]
sqlalchemy.exc.InternalError: (psycopg2.errors.IdleInTransactionSessionTimeout) terminating connection due to idle-in-transaction timeout
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

[SQL: REINDEX INDEX ref_geo.dem_st_convexhull_idx]
  ```

**Comment by camillemonchicourt** [comment]
Naïvement (et sans certitude) je dirai que le serveur sature en ressource quand il doit réindexé le MNT : https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/migrations/versions/1715cf31a75d_insert_ign_250m_bd_alti_in_dem.py#L53

Soit il faut vérifier ou augmenter les ressources du serveur, soit il faut indiquer de ne pas intégrer le MNT fourni par défaut lors de l'installation (https://github.com/PnX-SI/GeoNature/blob/master/config/settings.ini.sample#L57) et en intégrer un après coup manuellement (https://docs.geonature.fr/admin-manual.html#referentiel-geographique)

**Comment by remche** [comment]
Durant le reindex, ni la mémoire ni le CPU ne sont très sollicités.
Notez que la désactivation du timeout idle-in-transaction n'a pas eu d'effet...

Je vais essayer l'intégration du MNT après coup.

**Comment by Gaetanbrl** [comment]
@camillemonchicourt je me posais une question sur l'intégration de la BD Alti, est-ce qu'il serait pas aussi intéressant d'utiliser les service IGN pour ceux qui ne veulent pas intégrer tout la données de la BD Alti en base ?

L'IGN propose un service REST pour récupérer l'altimétrie d'un point :
 https://geoservices.ign.fr/documentation/services/api-et-services-ogc/calcul-altimetrique-rest

...via une requête du type :

` https://wxs.ign.fr/CLEF/alti/rest/elevation.json?lon=0.2367|2.1570&lat=48.0551|46.6077&zonly=true
`

Je ne sais pas s'il faut encore une clé (pas sur avec les dernières évolutions du service) et sinon ca reste une feature alternative à l'ajout de la BD Alti entière.

**Comment by gildeluermoz** [comment]
On utilisait ça dans gn1. Ça fonctionne bien. 
La limite c'est lors d'import en masse ou de besoin de recalculer les altitudes en nombre. Tu ne peux pas le faire en SQL.
A voir aussi ce qui est possible avec ce service pour retourner les altitudes min et max d'un polygone.

**Comment by gildeluermoz** [comment]
Il peut aussi être utile de bien régler les différents paramètres de postgresql.conf grâce à cet outil
[https://pgtune.leopard.in.ua/]()

**Comment by camillemonchicourt** [comment]
En effet j'allais répondre comme Gil.

**Comment by remche** [comment]
> Il peut aussi être utile de bien régler les différents paramètres de postgresql.conf grâce à cet outil https://pgtune.leopard.in.ua/

Merci pour le lien. Autant dans le second cas on a une conf quasi par défaut, autant dans le premier cas il s'agit d'un serveur mutualisé configuré _aux petits oignons_ qui héberge déjà un certain nombre de bases sans souci particulier !

L'installation passe effectivement tout droit si on n'installe pas le référentiel géographique. Je vais essayer de l'installer après coup.
