### ISSUE TITLE
Problème update configuration module synthèse

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#1892]
**Version**
2.9.2

**Description du bug**
Lorsque le paramètre AREA_FILTERS de la partie SYNTHESE de geonature_config.toml est ajouté, l'update_configuration plante.

**Comportement attendue**
L'update_configuration devrait fonctionner et les filtres définis s'afficher dans le module synthèse

**Comment reproduire**
Simplement ajouter les lignes suivantes dans la partie "SYNTHESE" du fichier geonature_config.toml, comme décrit dans la doc, puis relancer `geonature update_configuration `:

```
    AREA_FILTERS = [
        { label = "Communes", "type_code": "COM" },
        { label = "ZNIEFF1", "type_code": "ZNIEFF1" },
    ]
```

**Logs**
Pas de logs sur cette erreur, juste le retour sur le terminal suivant : 

```
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 662, in load_inline_object
    _, value = candidate_group.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 510, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 777, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 875, in load_value
    return (self.load_array(v), "array")
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 1021, in load_array
    nval, ntype = self.load_value(a[i])
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 878, in load_value
    self.load_inline_object(v, inline_object)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 664, in load_inline_object
    raise ValueError("Invalid inline table encountered")
ValueError: Invalid inline table encountered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 33, in <module>
    sys.exit(load_entry_point('geonature', 'console_scripts', 'geonature')())
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/geonatureadmin/geonature/backend/geonature/__init__.py", line 1, in <module>
    from .app import create_app
  File "/home/geonatureadmin/geonature/backend/geonature/app.py", line 22, in <module>
    from geonature.utils.config import config
  File "/home/geonatureadmin/geonature/backend/geonature/utils/config.py", line 13, in <module>
    config_backend = load_and_validate_toml(config_path, GnPySchemaConf)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/utilstoml.py", line 15, in load_and_validate_toml
    toml_config = load_toml(toml_file)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/utilstoml.py", line 29, in load_toml
    return toml.load(str(toml_file))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 513, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid inline table encountered (line 41 column 1 char 1336)

```

**Comment by DonovanMaillard** [comment]
Bonjour, 

Ca fonctionne de mon coté, avec la conf suivante : 

> AREA_FILTERS = [
        { label = "Espaces naturels (APB, RNN, RNR, Coeurs de Parcs, ENS...)", type_code = ["ZC", "APB", "RNN", "RNR", "RIPN", "ENS38", "ENS-L38"] },
        { label = "ZNIEFF 1", type_code = "ZNIEFF1"},
        { label = "Communes", type_code = "COM" },
        { label = "Autres découpages administratifs (Régions, Dpts, Métros, PNR, AA des PNX...)", type_code = ["PNR", "AA", "DEP", "METRO", "REG"] }
    ]

**Comment by cen-cgeier** [comment]
Salut, ça fonctionne également chez moi avec la config suivante :
```
    AREA_FILTERS = [
        { label = "Communes", type_code = "COM" },
        { label = "APB", type_code = "APB" },
        { label = "Sites CEN", type_code = "SCEN" },
        { label = "ZNIEFF1", type_code = "ZNIEFF1" },
    ]
```

L'erreur vient des `:` qui suivent `type_code`. Il faut un signe `=`
La déclaration de `type_code` semble fonctionner avec et sans guillemets.

**Comment by marie-laure-cen** [comment]
Bonjour,
L'erreur de : subsiste dans la documentation (configuration du module de synthèse) [https://docs.geonature.fr/admin-manual.html#module-synthese](url)
![synthse](https://github.com/PnX-SI/GeoNature/assets/143165944/5cd8652d-0941-4705-a346-0d2a9055e9b9)

**Comment by camillemonchicourt** [comment]
Bien vu, merci.
C'est corrigé pour la prochaine version - https://github.com/PnX-SI/GeoNature/commit/212ec61f1f89e824030f09efad24b124df604f39
