### ISSUE TITLE
Problème connexion

### ISSUE THREAD

**Issue by Uiio86** [PnX-SI/GeoNature#2031]
Bonjour, 

Suite à la modification du nom de domaine rattaché à nos applications Geonature, nous ne pouvons plus nous identifier.
Comme si les applications n'arrivaient plus à se connecter à la table des utilisateurs.
Alors que les identifiants n'ont pas été modifié.

Pourtant sans être connecté, Taxhub arrive bien à afficher les taxref ?!
J'avoue tout jute débuter avec Geonature et ne pas maitriser sa configuration.

Ce problème impacte Geonature, Taxhub et UsersHub.

Merci d'avance

**Comment by camillemonchicourt** [comment]
Oui il faut bien changer l'URL dans les fichiers de configuration et ensuite exécuter les commandes nécessaires à la prise en compte de ces modifications de la configuration.

**Comment by Uiio86** [comment]
J'ai vérifié les fichiers de configuration.
Et relancé les commandes de mise à jour de configuration : 

$ source backend/venv/bin/activate
$ geonature update_configuration
$ sudo systemctl restart geonature

Cependant j'ai une erreur lors de l'éxecution de cette commande : $ geonature update_configuration

Erreur : 
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1653, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1700, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 381, in load_app
    app = call_factory(self, self.create_app)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/home/geonatureadmin/geonature/backend/geonature/app.py", line 165, in create_app
    for module_object, module_config, module_blueprint in import_backend_enabled_modules():
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 104, in import_backend_enabled_modules
    yield import_gn_module(module_object)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 90, in import_gn_module
    module_config, module_blueprint = import_legacy_module(module_object)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 26, in import_legacy_module
    raise NoManifestFound()
geonature.utils.module.NoManifestFound

**Comment by camillemonchicourt** [comment]
Vous êtes sur quelle version de GeoNature ? 2.9.2 ?
http://192.168.1.25 est l'URL sur laquelle était GeoNature avant que vous ne changiez son URL pour un nom de domaine ?

PS : supervisor n'est plus utilisé dans GeoNature depuis sa version 2.8.0.

**Comment by camillemonchicourt** [comment]
Votre soucis est réglé ?

**Comment by Uiio86** [comment]
J'ai fini par tout réinstallé.
Merci de votre aide.
Je clôture le ticket
