### ISSUE TITLE
Edition de son propre JDD impossible

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#2176]
**Version**
2.9.2

**Description du bug**
Édition du JDD par son propriétaire impossible, message rouge "une erreur s'est produite".
Édition possible pour l'administrateur de GeoNature. 
L'édition d'un CA ne pose elle pas de problème. 
Peut faire penser à une erreur de CRUVED, mais j'ai essayé plusieurs modifications sans succès. 
Peut être lié au fait que mon schéma utilisateurs dans la BDD est un foreign schema d'une autre instance GeoNature. 

**Logs**
```
[2022-11-29 17:15:03 +0100] [2596429] [ERROR] Exception on /meta/dataset/9 [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 82, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_meta/routes.py", line 534, in update_dataset
    dataset = TDatasets.query.filter_by_readable().get_or_404(id_dataset)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 422, in get_or_404
    rv = self.get(ident)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_pk_identity
    q._get_condition()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 457, in _get_condition
    return self._no_criterion_condition(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 483, in _no_criterion_condition
    self._no_criterion_assertion(meth, order_by, distinct)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 477, in _no_criterion_assertion
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.get() being called on a Query with existing criterion.
```

**Comment by bouttier** [comment]
Je viens de vérifier dans le code de la 2.10.3 : c’est résolu : il n’y a plus d’endroit (dans le module méta-données) où on fait un ``get_or_404`` après un filtrage.

**Comment by bouttier** [comment]
Corrigé là : 44bca17eb78cb081561747dd69868a128e7cbf1c

**Comment by RNF-SI** [comment]
ok parfait, alors je vais faire la maj ;)

**Comment by camillemonchicourt** [comment]
En effet, tu peux soit reporter les modifications de ce commit sur ta 2.9 et redémarrer GeoNature (sans garantie de fonctionnement), soit faire ta mise à jour en 2.10 où cela est corrigé.
