### ISSUE TITLE
Interruption installation silencieuse [GeoNature 2.10.4]

### ISSUE THREAD

**Issue by MoulinZ** [PnX-SI/GeoNature#2191]
Rebonjour,

La MAJ à la 2.10.4 ne se passe pas comme prévu. En fait il ne se passe plus rien depuis 20 minutes, alors je ne sais pas si je peux me permettre de l'interrompre. 

Le dernier message est :
`Running upgrade 10e87bc144cd -> 112ccf1024ce, add unique constraint on t_roles UUID`

Ma conf est un peu particulière, vu que j'utilise le schema en foreign schema dans une autre instance geonature. Mais ici je ne vois pas pourquoi ça empêcherai quoi que ce soit...

Je ne sais pas si j'arrête tout pour retenter ? J'imagine que ça va poser problème...

**Comment by bouttier** [comment]
Est-ce que postgresql a l’air de faire quelque chose ? La contrainte d’unicité est peut-être tous simplement en train d’être créé, ce qui est peut-être très long à cause du foreign schema …

**Comment by jpm-cbna** [comment]
> vu que j'utilise le schema en foreign schema dans une autre instance geonature

Avec les `foreign data table`, je me suis rendu compte qu'il pouvait être très important d'augmenter la valeur du paramètre `fetch_size` qui vaut par défaut `100`. Dans mon cas, le problème concerné la table `synthese` avec plus de 10 millions de données et l'Atlas. Pour avoir des temps de réponse correcte de l'Atlas, j'ai passé la valeur à `1000000`.
Ceci dit, les deux bases sont sur le même serveur dans mon cas...

Pour ajouter cette option:
```sql
ALTER SERVER geonaturedbserver OPTIONS (ADD fetch_size '100000');
```
Pour la modifier:
```sql
ALTER SERVER geonaturedbserver OPTIONS (SET fetch_size '1000000');
```

**Comment by MoulinZ** [comment]
J'ai quand même une erreur sur la maj de mon mondule import (peut être liée à cette installation hachée) :
`la colonne t_imports.id_source_synthese n'existe pas`
Il y a une migration de bdd qui n'a pas du se faire ? Il est indiqué dans la note de version de GeoNature 2.10 qu'il faut simplement charger les modules sans faire les upgrade, mais dois-je appliquer cet upgrade quand même qui est indiqué dans la note de version de gn_module_import 2.0.0  :
```
geonature db stamp 4b137deaf201
geonature db autoupgrade
```

**Comment by camillemonchicourt** [comment]
Oui il faut, sinon le modèle de données d'Import ne sera pas réalisé...
Voir la fin de l'exemple de migration en 2.10 : https://geonature.fr/documents/procedures/2022-11-GN-210-Migrate.txt

**Comment by MoulinZ** [comment]
ok, j'ai donc une autre erreur ^^ :
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 4b137deaf201 -> 3a65de65b697, Refactoring of database structure
INFO  [alembic.runtime.migration] Running upgrade 3a65de65b697 -> 2ed6a7ee5250, Add two columns
INFO  [alembic.runtime.migration] Running upgrade 2ed6a7ee5250 -> 75f0f9906bf1, add_columns
INFO  [alembic.runtime.migration] Running upgrade 75f0f9906bf1 -> bf80cb5679be, remove step field
INFO  [alembic.runtime.migration] Running upgrade bf80cb5679be -> 6470a2141c83, mappings
INFO  [alembic.runtime.migration] Running upgrade 6470a2141c83 -> 906231e8f8e0, remove temporary tables
INFO  [alembic.runtime.migration] Running upgrade 906231e8f8e0 -> 0e4f9da0e33f, remove in_error column
INFO  [alembic.runtime.migration] Running upgrade 0e4f9da0e33f -> 61e11414f177, add detected separator
INFO  [alembic.runtime.migration] Running upgrade 61e11414f177 -> 74058f69828a, remove t_imports.is_finished
INFO  [alembic.runtime.migration] Running upgrade 74058f69828a -> eb217f32d7d7, add id_area_attachment
INFO  [alembic.runtime.migration] Running upgrade eb217f32d7d7 -> 681062ef2939, add date error
INFO  [alembic.runtime.migration] Running upgrade 681062ef2939 -> 699c25251384, Update fields and themes
INFO  [alembic.runtime.migration] Running upgrade 699c25251384 -> 627b7968a55b, date min/max too low
INFO  [alembic.runtime.migration] Running upgrade 627b7968a55b -> cadfdaa42430, add task_uuid
INFO  [alembic.runtime.migration] Running upgrade cadfdaa42430 -> 6f60b0b934b1, erroneous rows
INFO  [alembic.runtime.migration] Running upgrade 6f60b0b934b1 -> 0ff8fc0b4233, remove_archive_schema
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/sql/base.py:299: SAWarning: Can't validate argument 'dialect_options'; can't locate any SQLAlchemy dialect named 'dialect'
  util.warn(
INFO  [alembic.runtime.migration] Running upgrade 0ff8fc0b4233 -> 5c31e356cedc, add loaded column
INFO  [alembic.runtime.migration] Running upgrade 5c31e356cedc -> f394a5edcb56, on delete source set null
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: ERREUR:  la contrainte « fk_gn_imports_t_import_id_source_synthese » de la relation « t_imports » n'existe pas

```

**Comment by bouttier** [comment]
As-tu bien appliqué ``1.1.8to1.2.0.sql`` ?
