### ISSUE TITLE
Installation geonature2: Port could not be cast to integer value as 'geonat'

### ISSUE THREAD

**Issue by juliettefabre** [PnX-SI/GeoNature#2222]
**Version**
2.10.4

**Description du bug**
Je rencontre un problème à l'installation, en exécutant le script install_all.sh
[...]
INFO  [alembic.runtime.migration] Created temporary directory '/tmp/tmpwswei_85'
INFO  [alembic.runtime.migration] Downloading 'referentiel_donnees_sensibles_v13.csv.xz'…
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 1715cf31a75d, Insert default French DEM (IGN 250m BD alti)
INFO  [alembic.runtime.migration] Created temporary directory '/tmp/tmpa_zdjpar'
INFO  [alembic.runtime.migration] Downloading 'BDALTIV2_2-0_250M_ASC_LAMB93-IGN69_FRANCE_2017-06-21.zip'…
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_migrate/cli.py", line 149, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_migrate/__init__.py", line 98, in wrapped
    f(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_migrate/__init__.py", line 185, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/geonatureadmin/geonature/backend/geonature/migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "/home/geonatureadmin/geonature/backend/geonature/migrations/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
    step.migration_fn(**kw)
  File "/home/geonatureadmin/geonature/backend/geonature/migrations/versions/1715cf31a75d_insert_ign_250m_bd_alti_in_dem.py", line 43, in upgrade
    "PGPORT": str(db_uri.port),
  File "/usr/lib/python3.9/urllib/parse.py", line 175, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'geonat'

Pourtant je n'ai pas touché au port PG dans le fichier install_all.ini (5432) ...

**Comment by camillemonchicourt** [comment]
Il doit forcément quelque chose de mal renseigné quelque part, car le message d'erreur indique que vous avez passé la valeur ``geonat`` au paramètre du port, donc un texte alors qu'il attend un entier et donc ça bloque.

On a fait pas mal de tests du script install_all sur la version 2.10 et j'en ai refait un avant-hier sur la version 2.10.4 donc je pense vraiment à un soucis de renseignement des paramètres dans le fichier ``install_all.ini``.

Pouvez-vous vérifier ou nous préciser le contenu de ce fichier ?

PS : Il est possible de relancer le script ``install_all.sh`` sur le même serveur, mais il faut au préalable supprimer le répertoire ``geonature`` sur le serveur et passer le paramètre ``drop_geonaturedb`` à ``true`` dans le fichier ``install_all.ini`` avant de relancer le script ``install_all.sh``

**Comment by geobrun** [comment]
Il me semble que cela ressemble au problème que j'avais rencontré par le passé au niveau des caractères spéciaux des mots de passe. Tu n'as pas un mot de passe avec "geonat" suivi d'un caractère spécial, genre #, ! ou ?

**Comment by juliettefabre** [comment]
J'ai relancé après avoir changé le nom d'utilisateur dans la config, c'est en cours !
Les caractères spéciaux / chiffres dans le mdp doivent perturber le parsing de l'url dans le script "/home/geonatureadmin/geonature/backend/geonature/migrations/versions/1715cf31a75d_insert_ign_250m_bd_alti_in_dem.py" ?

**Comment by juliettefabre** [comment]
Visiblement avec la modif du mot de passe et du nom d'utilisateur tout s'est bien passé niveau PG. Merci !

En revanche l'exécution s'arrête ainsi, j'imagine que ce n'est pas normal ..
```
✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.
- Generating ES5 bundles for differential loading...
Killed
```

**Comment by camillemonchicourt** [comment]
Là c'est ton serveur dont la RAM sature et n'arrive pas à builder le frontend de GeoNature. Ca peut être lié au fait que tu as fait plusieurs tentatives d'installation et qu'il fatigue. 

Soit tu redémarres ton serveur et tu relances un ``install_all.sh`` et ça passe, soit ton serveur n'a pas assez de ressources pour faire tourner GeoNature.

**Comment by juliettefabre** [comment]
OK merci !

**Comment by camillemonchicourt** [comment]
Concernant les problèmes de caractères spéciaux dans le mot de passe de la BDD, voir aussi https://github.com/PnX-SI/GeoNature/issues/2112.

Sujet que l'on doit investiguer, clarifier de notre côté.

**Comment by juliettefabre** [comment]
Bon j'ai réussi à installer geonature, mais en désactivant l'import de la BD ALTI (`install_default_dem=false`).

Je n'avais plus le message d'erreur de port PG, mais la commande `Processing 1/1: /tmp/tmpjtdd5nsm/BDALTIV2_250M_FXX_0098_7150_MNT_LAMB93_IGN69.asc` ne semblait pas aboutir (j'ai laissé tourner une petite heure je pense) . Je ré-essaierai quand même.

**Comment by camillemonchicourt** [comment]
Oui l'intégration du MNT peut être longue.
Mais pas une heure généralement.

Donc soit votre serveur a peu de ressources et met très longtemps, soit il n'en pas assez et n'arrive pas à mener au bout cette intégration.
