### ISSUE TITLE
erreur sur un des filtres avancés

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2235]
**Version 2.9.2 mais aussi 2.10.1 de la demo**

**Description du bug**
Le filtre avancé statut biogéographique" dans la synthèse, GN (2.9.2) remonte une erreur. 

**Comment reproduire**
Choisir le filtre avancé "statut biogéographique" sur [demo.geonature.fr/geonature](http://demo.geonature.fr/geonature) et lancer la recherche

**Logs**
```
Traceback (most recent call last):
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonature/geonature/backend/geonature/core/gn_permissions/decorators.py", line 82, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonature/geonature/backend/geonature/core/gn_synthese/routes.py", line 151, in get_observations_for_web
    synthese_query_class.filter_query_all_filters(info_role)
  File "/home/geonature/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 371, in filter_query_all_filters
    self.filter_other_filters()
  File "/home/geonature/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 340, in filter_other_filters
    col = getattr(self.model.__table__.columns, colname)
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: id_nomenclature_biogeo_status
[2022-12-15 15:46:50 +0100] [993832] [ERROR] Exception on /synthese/for_web [POST]
Traceback (most recent call last):
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'id_nomenclature_biogeo_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonature/geonature/backend/geonature/core/gn_permissions/decorators.py", line 82, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonature/geonature/backend/geonature/core/gn_synthese/routes.py", line 151, in get_observations_for_web
    synthese_query_class.filter_query_all_filters(info_role)
  File "/home/geonature/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 371, in filter_query_all_filters
    self.filter_other_filters()
  File "/home/geonature/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 340, in filter_other_filters
    col = getattr(self.model.__table__.columns, colname)
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: id_nomenclature_biogeo_status
```

**Comment by DonovanMaillard** [comment]
Bonjour, 

En effet, constaté également sur la 2.11 et la 2.12, erreur quand on veut filtrer par statut biogéographique :) 

Un truc que je ne comprends pas, c'est qu'on appelle une nomenclature. Cette info devrait être récupérée au niveau de l'id_statut du taxref plutôt, non ?

**Comment by bouttier** [comment]
Bien que présente dans la table `synthese`, la nomenclature est manquante dans la vue `v_synthese_for_web_app`

**Comment by bouttier** [comment]
Il faudrait supprimer la vue ``V_synthese_for_web_app`` au profit de l’utilisation du modèle `Synthese`.

**Comment by camillemonchicourt** [comment]
En attendant, ça ne vaut pas le coup d'ajouter le champs dans la vue ? 😇

**Comment by christophe-ramet** [comment]
> En attendant, ça ne vaut pas le coup d'ajouter le champs dans la vue ? 😇

Le problème a été remonté recemment sur une de nos instance. Je te rejoins Camille, le quickfix semble simple

**Comment by camillemonchicourt** [comment]
Fait dans la 2.17.2.
A terme, il serait plutôt préférable de supprimer la vue `v_synthese_for_web_app` comme indiqué plus haut.
