### ISSUE TITLE
Erreur pour la mise à jour de GN 2.9.2 à 2.10.4

### ISSUE THREAD

**Issue by adyulome09** [PnX-SI/GeoNature#2297]
**Version**
GN 2.10.4

**Description du bug**
Bug similaire à #2227.

**Problème lors de la mise à jour de GN 2.9.2 à 2.10.4** 
GN 2.9.2 vers 2.10.4
UH 2.2.1 vers 2.3.1
TH 1.9.1 vers 1.10.4
Import 1.2.0 vers 2.0.1
Monitoring 0.2.9 vers 0.3.0
J'ai suivi les indications de la procédure comme mentionné sur l'exemple (https://geonature.fr/documents/procedures/2022-11-GN-210-Migrate.txt).
A la fin de l'installation, le message suivant s'affiche :

```
✔ Browser application bundle generation complete.
⠏ Generating ES5 bundles for differential loading...Killed

Migration terminée
```
`
geonature db status` a l'air ok.
```
(venv) geonatureadmin@vps-b46885bc:~/geonature$ geonature db status
Context impl PostgresqlImpl.
Will assume transactional DDL.
[geonature ✓]
  [x] ┰ f06cc80cc8ba geonature schemas 2.7.5
  [x] ┃ c0fdf2ee7f4f auto update cor_area_synthese
  [x] ┃ 7077aa76da3d bump dependencies
  [x] ┃ 2a2e5c519fd1 fix gn_synthese.get_default_nomenclature_value
  [x] ┃ 5f4c4b644844 delete cascade on  cor_dataset_territory and cor_dataset_protocol
  [x] ┃ 2aa558b1be3a add schema gn_profiles
  [x] ┃ 1eb624249f2b add default value in additionalFields bib
  [x] ┃ 7471f51011c8 change index_vm_valid_profiles_cd_ref to unique index
  [x] ┃ 6f7d5549d49e delete view v_synthese_validation_forwebapp
  [x] ┣┓ dde31e76ce45 remove old profile function
  [x]  ┃ 61e46813d621 Update synthese sensitivity
  [x]  ┃ dfec5f64ac73 Fix sensitivity algorithm
  [x]  ┃ ac08dcf3f27b Do not auto-compute diffusion_level
  [x] ┃ 30edd97ae582 Remove gn_export.t_config_exports
  [x] ┣┛ 1dbc45309d6e Merge sensitivity
  [x] ┃ ca052245c6ec remove local srid
  [x] ┃ 095da7bc6667 add table gn_synthese.bib_reports_types
  [x] ┃ 829a376daa52 add table gn_synthese.t_reports
  [x] ┃ ca0fe5d21ea2 remove v_synthese_decode_nomenclatures
  [x] ┃ 74908bad752e add_altitude_calculation_in_t_base_site
  [x] ┃ 77a3bc6628d2 additional fields: add datalist widget
  [x] ┃ d80835fb13c8 Remove gn_sensitivity.cor_sensitivity_synthese
  [x] ┃ 6070edb31013 Set constraint check_cor_af_territory NOT VALID
  [x] ┃ f4ffdc68072c add id_module in t_sources
  [x] ┃ 8d90ab5e686d Add profiles default parameters
  [x] ┃ 07f10bbb4f3b add mobile app settings url
  [x] ┃ 42040535a20e add ng_module column in t_modules
  [x] ┸ 4b5478df71cb Update synthese sensitivity, including previously NULL rows
[geonature-samples ✓]
  [x] ─ 3d0bf4ee67d1 geonature samples
[habitats ✓]
  [x] ─ 62e63cd6135d create ref_habitats schema
[habitats_inpn_data ✓]
  [x] ┰ 46e91e738845 insert inpn data in ref_habitats schema
  [x] ┸ 805442837a68 correction on habref data
[ign_bd_alti]
  [ ] ─ 1715cf31a75d Insert default French DEM (IGN 250m BD alti)
[ign_bd_alti_vector]
  [ ] ─ 87651375c2e8 Vectorize French DEM
[import ✓]
  [x] ┰ 4b137deaf201 create_import_schema
  [x] ┃ 3a65de65b697 Refactoring of database structure
  [x] ┃ 2ed6a7ee5250 Add two columns
  [x] ┃ 75f0f9906bf1 add_columns
  [x] ┃ bf80cb5679be remove step field
  [x] ┃ 6470a2141c83 mappings
  [x] ┃ 906231e8f8e0 remove temporary tables
  [x] ┃ 0e4f9da0e33f remove in_error column
  [x] ┃ 61e11414f177 add detected separator
  [x] ┃ 74058f69828a remove t_imports.is_finished
  [x] ┃ eb217f32d7d7 add id_area_attachment
  [x] ┃ 681062ef2939 add date error
  [x] ┃ 699c25251384 Update fields and themes
  [x] ┃ 627b7968a55b date min/max too low
  [x] ┃ cadfdaa42430 add task_uuid
  [x] ┃ 6f60b0b934b1 erroneous rows
  [x] ┃ 0ff8fc0b4233 remove_archive_schema
  [x] ┃ 5c31e356cedc add loaded column
  [x] ┃ f394a5edcb56 on delete source set null
  [x] ┃ 65defbe5027b set id_module on import sources
  [x] ┸ a11c9a2db7bb set import module type
[nomenclatures ✓]
  [x] ┰ 6015397d686a create ref_nomenclature schema 1.3.9
  [x] ┃ 11e7741319fd fix ref_nomenclatures.get_default_nomenclature_value
  [x] ┃ f8c2c8482419 fix ref_nomenclatures.get_default_nomenclature_value
  [x] ┸ b820c66d8daa fix ref_nomenclatures.get_nomenclature_label
[nomenclatures_inpn_data ✓]
  [x] ┰ 96a713739fdd insert inpn data in ref_nomenclatures
  [x] ┃ 618542880d1f fix typo in nomenclature type definition
  [x] ┸ ee1146f6c0f4 Add UICN Red List
[nomenclatures_taxonomie ✓]
  [x] ─ f5436084bf17 add support for taxonomy into ref_nomenclatures
[nomenclatures_taxonomie_data]
  [ ] ─ a763fb554ff2 insert taxonomic filtering data in ref_nomenclatures.cor_taxref_nomenclatures
[occhab ✓]
  [x] ─ 2984569d5df6 create occhab schema
[occhab-samples ✓]
  [x] ─ 21f661247023 insert occhab sample data
[occtax ✓]
  [x] ┰ 29c199e07eaa create occtax schema
  [x] ┃ addb71d8efad create occtax export view
  [x] ┃ f57107d2d0ad fix get_default_nomenclature_value
  [x] ┃ 494cb2245a43 trigger comportement
  [x] ┃ 944072911ff7 update synthese data (bug occtax trigger)
  [x] ┃ 22c2851bc387 add database default value
  [x] ┃ 023b0be41829 add id_module in pr_occtax.t_releves
  [x] ┃ c26c770b00ae fix occtax trigger additionnal data + trigger occ
  [x] ┃ 9624348fea40 restore occtax missing counting
  [x] ┃ 576cbd26b012 default value for id_nomenclature_observations_status
  [x] ┸ 61802a0f83b8 Fix OccTax triggers to synthese
[occtax-samples ✓]
  [x] ─ cce08a64eb4f insert occtax sample data
[occtax-samples-test]
  [ ] ─ 2a0ab7644e1c occtax sample test
[ref_geo ✓]
  [x] ┰ 6afe74833ed0 ref_geo schema
  [x] ┃ e0ac4c9f5c0a add indexes on FK referencing l_areas.id_area
  [x] ┃ 4882d6141a41 add regions in area types
  [x] ┃ 681306b27407 fix altitude trigger
  [x] ┃ cb038e76d59c fix functions local srid
  [x] ┸ f7374cd6e38d add linears
[ref_geo_fr_departments ✓]
  [x] ─ 3fdaa1805575 Insert French departments in ref_geo
[ref_geo_fr_municipalities ✓]
  [x] ─ 0dfdbfbccd63 Insert French municipalities in ref_geo
[ref_geo_fr_regions]
  [ ] ─ d02f4563bebe Insert French regions in ref_geo
[ref_geo_fr_regions_1970]
  [ ] ─ 05a0ae652c13 Insert French regions 1970-2016 in ref_geo
[ref_geo_inpn_grids_1 ✓]
  [x] ─ 586613e2faeb Insert INPN 1×1 grids in ref_geo
[ref_geo_inpn_grids_10 ✓]
  [x] ─ ede150d9afd9 Insert INPN 10×10 grids in ref_geo
[ref_geo_inpn_grids_5 ✓]
  [x] ─ 7d6e98441e4c Insert INPN 5×5 grids in ref_geo
[ref_sensitivity_inpn]
  [ ] ─ 7dfd0a813f86 Insert INPN rules in sensitivity referential
[sql_utils ✓]
  [x] ┰ 3842a6d800a0 Add public shared functions
  [x] ┸ ba207b468e31 create fr_numeric collation
[taxhub ✓]
  [x] ┰ fa5a90853c45 taxhub
  [x] ┸ 64d38dbe7739 taxonomie
[taxhub-admin ✓]
  [x] ─ 3fe8c07741be taxhub
[taxonomie ✓]
  [x] ┰ 9c2c0254aadc create taxonomie schema version 1.8.1
  [x] ┃ 7540702c6407 cd_ref utility functions
  [x] ┃ 98035939bc0d find_all_taxons_parents
  [x] ┃ c93cbb35cfe4 set default value for id_liste
  [x] ┃ 4fb7e197d241 create taxonomie.v_bdc_status view
  [x] ┃ d768a5da908c add bdc_status indexes
  [x] ┃ 4a549132d156 Add unique constraints
  [x] ┃ c4415009f164 Taxref v15 db structure
  [x] ┃ 1b1a3f5cd107 Add table to link bdc_status and ref_geo
  [x] ┸ f2c36312b3de fix vm_taxref_for_autocomplete
[usershub ✓]
  [x] ┰ 9445a69f2bed UsersHub
  [x] ┸ 6ec215fe023e upgrade utilisateurs schema
[usershub-samples ✓]
  [x] ─ f63a8f44c969 UsersHub samples data
[utilisateurs ✓]
  [x] ┰ fa35dfe5ff27 utilisateurs schema 1.4.7 (usershub 2.1.3)
  [x] ┃ 830cc8f4daef add additional_data field to bib_organismes
  [x] ┃ 5b334b77f5f5 fix v_roleslist_forall_applications
  [x] ┃ 951b8270a1cf add unique constraint on bib_organismes.uuid_organisme
  [x] ┃ 10e87bc144cd get_id_role_by_name()
  [x] ┸ 112ccf1024ce add unique constraint on t_roles UUID
[utilisateurs-samples ✓]
  [x] ─ 72f227e37bdf utilisateurs sample data

```
 `geonature db autoupgrade` OK

`geonature db upgrade monitoring@head` renvoi l'erreur 

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [flask_migrate] Error: Can't locate revision identified by 'monitoring'

```
`geonature update-module-configuration monitoring` erreur sur un problème de nom
```
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/geonature/utils/gn_module_import.py", line 380, in create_module_config
    module_object = TModules.query.filter_by(module_code=module_code).one()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 348, in update_module_configuration
    create_module_config(module_code, output_file)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/gn_module_import.py", line 382, in create_module_config
    raise Exception(f"Module with code '{module_code}' not found in database.")
Exception: Module with code 'MONITORING' not found in database.
```
J'ai changer le nom dans la table `gn_commons.t_modules` colonne `module_code` de `MONITORINGS `en `MONITORING` et plus de message erreur avec `geonature update-module-configuration monitoring`.
`geonature db upgrade monitoring@head` renvoi toujours la même erreur 
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [flask_migrate] Error: Can't locate revision identified by 'monitoring'
```
`geonature update-configuration `renvoi cette erreur

```
Generating configuration
...ok


Found '/home/geonatureadmin/geonature/frontend/.nvmrc' with version <v16.13.2>
Now using node v16.13.2 (npm v8.1.2)

> geonature@0.0.0 build
> ng build --aot=false --build-optimizer=false --configuration production

Warning: Support was requested for IE 11 in the project's browserslist configuration. IE 11 support is deprecated since Angular v12.
For more information, see https://angular.io/guide/browser-support
✔ Browser application bundle generation complete.

Warning: /home/geonatureadmin/geonature/frontend/src/app/app.module.ts depends on 'angular2-chartjs'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/app/app.module.ts depends on 'ng2-cookies'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/app/metadataModule/services/metadata-search-form.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/src/app/syntheseModule/services/form.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/src/app/syntheseModule/services/store.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-info-obs/modal-info-obs.component.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.



../external_modules/monitoring/frontend/app/gnModule.module.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /home/geonatureadmin/geonature/external_modules/monitoring/frontend/app/gnModule.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at /home/geonatureadmin/geonature/frontend/node_modules/@ngtools/webpack/src/ivy/loader.js:59:26


Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/main.py", line 109, in update_configuration
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/bash', '-i', '-c', 'nvm use && npm run build']' returned non-zero exit status 1.
```

Avez-vous une idées de comment déméler tous ça?

**Comment by camillemonchicourt** [comment]
L'erreur que vous remontez a été évoquée dans plusieurs tickets : 

```
✔ Browser application bundle generation complete.
⠏ Generating ES5 bundles for differential loading...Killed
```

Elle indique que votre serveur était saturé au niveau de ses ressources et n'a pas réussi à aller au bout du build du frontend.

Il faudrait tenter de redémarrer le serveur pour soulager ses ressources et relancer ce build avec : 
```
cd ~/geonature/frontend
nvm use
npm run build
```

Si cela refait la même erreur, cela veut dire que le serveur n'a toujours pas assez de ressources pour builder le frontend. Mais ça serait étonnant car vous l'avez déjà fait en version 2.9.

-----------------------------------

Pour les erreurs suivantes, il y a peut-être une confusion car le module MONITORING n'était pas géré avec Alembic dans sa version 0.3.0, seulement à partir de sa version 0.4.0 compatible avec GeoNature 2.11.0 et plus.
Donc il n'y a pas à lancer ``geonature db upgrade monitoring@head`` et cette commande ne peut pas fonctionner selon moi tant que le module n'est pas en version 0.4.0 ou plus.
Et en effet, il y a un truc qui a cafouillé dans le module Monitoring et son fichier de config.
Mais je laisse @bouttier, plus pointu que moi sur le sujet, répondre.

PS : Il est plus simple et plus efficace de passer directement de la version 2.9 à 2.11. 
Ma procédure testée : https://geonature.fr/documents/procedures/2023-01-GN-29to211.txt

**Comment by bouttier** [comment]
Bonjour,
Il faut remettre `MONITORINGS` dans la colonne `module_code` : https://github.com/PnX-SI/gn_module_import/blob/master/backend/gn_module_import/__init__.py#L1
Et utiliser la commande `geonature update-module-configuration MONITORINGS`
S’il reste des soucis, tenter de réinstaller le module avec la commande `geonature install-packaged-gn-module ~/gn_module_monitoring/ MONITORINGS` (2.10) ou `geonature install-gn-module ~/gn_module_monitoring/ MONITORINGS` (2.11).

**Comment by adyulome09** [comment]
Bonjour,
Bon tout fonctionne. J'ai repris la migration en passant de GN 2.9.2 à 2.11 comme suggéré par [Camille Monchicourt](https://github.com/camillemonchicourt). J'ai fait la mise à jour de module monitoring après l’inhalation GN 2.11.
Encore un grand merci pour votre aide précieuse.
