### ISSUE TITLE
[GN -  2.11.2] Recovery Password - users/login/recovery

### ISSUE THREAD

**Issue by pierre56** [PnX-SI/GeoNature#2401]
**Version**
GeoNature -  2.11.2
UsersHub - 2.3.3

**Description du bug**
Il n'est pas possible de demander le changement de son mot de passe.
![image](https://user-images.githubusercontent.com/26764293/225877681-f358a2e8-d49d-4d8f-9b47-74742afc0924.png)
![image](https://user-images.githubusercontent.com/26764293/225878149-1ab1230c-01f5-4033-9053-002f72329b22.png)

A la base, j'avais une erreur 502 et je pensais que ça venait du timeout de gunicorn.
Donc je l'ai augmenté et mnt j'ai une erreur 500 claire dans les logs.

**Comportement attendue**
Réception du mail pour changer le mot de passe.
Si possible il faut qu'un utilisateur ayant un compte actif mais sans password, soit en capacité de demander un mot de passe.
( J'ai plus de 10K utilisateurs sans mdp car j'ai intégré les comptes utilisateurs provenant de Faune Bretagne)

**Comment reproduire**

1. Se rendre sur la page de login : https://geonature.bretagne-vivante.org/#/login
2. Cliquer sur "identifiant oublié"
3. Rentrer sur adresse mail valide avec un compte actif.
4. Cliquer sur "envoyer"

**Logs**

```
[f42993b9-0ce9-4c41-98a3-dd8f961c1fc7] Exception on /users/login/recovery [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2ec81e4880>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geonature.bretagne-vivante.org', port=443): Max retries exceeded with url: /api/pypn/register/post_usershub/create_cor_role_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2ec81e4880>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/users/routes.py", line 260, in login_recovery
    r = s.post(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='geonature.bretagne-vivante.org', port=443): Max retries exceeded with url: /api/pypn/register/post_usershub/create_cor_role_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2ec81e4880>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-03-17 11:06:12 +0100] [10858] [ERROR] Exception on /users/login/recovery [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2ec81e4880>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geonature.bretagne-vivante.org', port=443): Max retries exceeded with url: /api/pypn/register/post_usershub/create_cor_role_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2ec81e4880>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/users/routes.py", line 260, in login_recovery
    r = s.post(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='geonature.bretagne-vivante.org', port=443): Max retries exceeded with url: /api/pypn/register/post_usershub/create_cor_role_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2ec81e4880>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

## Tickets associés (?)
https://github.com/urllib3/urllib3/issues/2534
https://github.com/PnX-SI/GeoNature/issues/944
https://github.com/PnX-SI/UsersHub-authentification-module/issues/29
https://github.com/PnX-SI/GeoNature/issues/2288

## Remarque complémentaire

Ma configuration mail est fonctionnelle, j'arrive a envoyer des mails sans soucis via le module export.
Je ne comprends pas pourquoi la connexion est refusée car tout le reste fonctionne entre geonature et usershub 😓 

J'ai l'impression que ça vient de "create_cor_role_token" mais pas sur...

Si vous avez une piste je suis preneur, 
Merci 😄

**Comment by camillemonchicourt** [comment]
Ah pourtant on avait réglé des trucs sur ce sujet dans UsersHub 2.3.3 et je pensais que c'était réglé.

**Comment by pierre56** [comment]
> Ah pourtant on avait réglé des trucs sur ce sujet dans UsersHub 2.3.3 et je pensais que c'était réglé.

Oui j'ai vu https://github.com/PnX-SI/GeoNature/issues/2288
et le fix :
https://github.com/PnX-SI/UsersHub/commit/3a10a354679feeeab57437bc4254b3f8d21e738b

mais j'ai vérifié et je suis bon :/
![image](https://user-images.githubusercontent.com/26764293/225884938-ade40ea4-cbd7-4069-8959-5cde41dc87f0.png)

**Comment by mvergez** [comment]
Salut !
je ne sais pas si ça peut t'aider mais quand j'ai ce genre de souci de connection, j'essaie de faire la requête "à la main" c'est à dire, pour ton cas, faire un POST avec la commande `curl` directement depuis le serveur. Pour voir si ton serveur peut atteindre en https `geonature.bretagne-vivante.org`. 

Après là c'est un connection refused... Comme si le service ne répondait pas. Tu as pu voir les logs de usershub ?

**Comment by pierre56** [comment]
> Salut ! je ne sais pas si ça peut t'aider mais quand j'ai ce genre de souci de connection, j'essaie de faire la requête "à la main" c'est à dire, pour ton cas, faire un POST avec la commande `curl` directement depuis le serveur. Pour voir si ton serveur peut atteindre en https `geonature.bretagne-vivante.org`.
> 
> Après là c'est un connection refused... Comme si le service ne répondait pas. Tu as pu voir les logs de usershub ?

Salut @mvergez ,
Je ne vois pas trop comment gérer via curl a cause du token 🤔 

## var/log/usershub
```
[2023-03-17 11:04:44 +0100] [3103] [INFO] Worker exiting (pid: 3103)
[2023-03-17 11:04:44 +0100] [3102] [INFO] Worker exiting (pid: 3102)
[2023-03-17 11:04:44 +0100] [3099] [INFO] Handling signal: term
[2023-03-17 11:04:44 +0100] [3101] [INFO] Worker exiting (pid: 3101)
[2023-03-17 11:04:44 +0100] [3099] [WARNING] Worker with pid 3102 was terminated due to signal 15
[2023-03-17 11:04:44 +0100] [3100] [INFO] Worker exiting (pid: 3100)
[2023-03-17 11:04:44 +0100] [3099] [WARNING] Worker with pid 3103 was terminated due to signal 15
[2023-03-17 11:04:44 +0100] [3099] [INFO] Shutting down: Master
[2023-03-17 11:04:45 +0100] [11043] [INFO] Starting gunicorn 20.1.0
[2023-03-17 11:04:45 +0100] [11043] [INFO] Listening at: http://127.0.0.1:5001 (11043)
[2023-03-17 11:04:45 +0100] [11043] [INFO] Using worker: sync
[2023-03-17 11:04:45 +0100] [11045] [INFO] Booting worker with pid: 11045
[2023-03-17 11:04:45 +0100] [11046] [INFO] Booting worker with pid: 11046
[2023-03-17 11:04:45 +0100] [11047] [INFO] Booting worker with pid: 11047
[2023-03-17 11:04:45 +0100] [11048] [INFO] Booting worker with pid: 11048

``` 
> Rien d'intéressant

## error-geonature.log
``` 

[Fri Mar 17 09:57:12.730773 2023] [proxy_http:error] [pid 5869:tid 140104903415552] (20014)Internal error (specific information not available): [client 192.168.30.2:37260] AH01102: error reading status line from remote server 127.0.0.1:8000, referer: https://geonature.bretagne-vivante.org/ [Fri Mar 17 09:57:12.731030 2023] 
[proxy:error] [pid 5869:tid140104903415552] [client 192.168.30.2:37260] AH00898: Error reading from remote server returned by /api/users/login/recovery, referer: https://geonature.bretagne-vivante.org/
``` 

Piste intéressante, proxy_http:error et proxy:error mais je vois pas trop comment régler le soucis 😅 
Je vais fouiller ...

**Comment by mvergez** [comment]
Ah oui en effet...

Tu as l'air d'avoir le backend de Usershub qui crash, ou alors l'as tu redémarré ? : `[2023-03-17 11:04:44 +0100] [3099] [WARNING] Worker with pid 3103 was terminated due to signal 15`

**Comment by pierre56** [comment]
> Ah oui en effet...
> 
> Tu as l'air d'avoir le backend de Usershub qui crash, ou alors l'as tu redémarré ? : `[2023-03-17 11:04:44 +0100] [3099] [WARNING] Worker with pid 3103 was terminated due to signal 15`

@mvergez 
Je l'ai redémarré a plusieurs reprises pour prendre en compte mes modifs.
ça pollue un peu les logs :/

je suspecte que ça vienne d'un pb entre apache et gunicorn, j'ai essayé d'augmenté les timeout, de changer des trucs dans la config apache mais pas grand rendu.
Les différents sites sont sur leur propre sous-domaines et ils ont l'air de communiquer entre eux, vu qu'il n'y a que ça qui déconne.

-----
Mais j'ai exactement les mm symptômes que  https://github.com/PnX-SI/GeoNature/issues/944

Je peux modifier le mdp via usershub.
Mais pas via l'interface de login
ou via la page compte lorsque connecté.

A chaque fois, c'est la route /api/users/login/recovery qui déconne.

Fichier qui semble suspect :
/home/geonatureadmin/geonature/backend/geonature/core/users/register_post_actions.py
/home/geonatureadmin/usershub/app/api/route_register.py

-----

D'ailleurs en explorant le code, je vois qu'il faut un token qui est stocké en BDD dans la table utilisateurs.cor_role_token .
Si l'utilisateur a été généré automatiquement, le token n'est pas créé donc ce ne sera pas possible pour un user sans mdp de demander l'envoi de son mdp ?
je comprends de moins en moins comment fonctionne l'authent et les routes entre Usershub et geonature...

**Comment by jbrieuclp** [comment]
La création ou la modif des info de compte est fonctionnelle ?
Ce n'est pas une mauvaise config du bloc USERSHUB de ton fichier `geonature_config.toml`
```
[USERSHUB]
    URL_USERSHUB = "http://127.0.0.1:5001"
    ADMIN_APPLICATION_LOGIN = ***
    ADMIN_APPLICATION_PASSWORD = ***
```

Pour le token avec curl tu peux suivre cet exemple :
```
curl --location --request POST 'https://outils.gretia.org/geonature/api/synthese/for_web' --header 'Cookie: token=TON_TOKEN'
```
ou utiliser Postman aussi, c'est pas mal

**Comment by pierre56** [comment]
> URL_USERSHUB = "http://127.0.0.1:5001"

Merci pour la piste @jbrieuclp 
J'avais pas pensé à la config
mais j'ai testé 2 versions et aucune ne change le pb :/

```
[USERSHUB]
    #URL_USERSHUB = "http://127.0.0.1:5001"
    URL_USERSHUB = "https://usershub.bretagne-vivante.org"
    # Administrateur de mon application
    ADMIN_APPLICATION_LOGIN = "***"
    ADMIN_APPLICATION_PASSWORD = "***"
```

Mais malheureusement tjrs le mm pb 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/users/routes.py", line 260, in login_recovery
    r = s.post(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='geonature.bretagne-vivante.org', port=443): Max retries exceeded with url: /api/pypn/register/post_usershub/create_cor_role_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0b1a44abb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

```
Je vais laisser comme ça pour le moment, je m'y remets la semaine pro...
Bon week-end 😄

**Comment by gildeluermoz** [comment]
T'as pas un pare-feu qui bloquerait le port 443 en input ou output ?

**Comment by camillemonchicourt** [comment]
OK
