### ISSUE TITLE
[2.12.0] Erreur 500 - api/meta/datasets?orderby=dataset_name [POST]

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/GeoNature#2454]
Bonjour à tous,
**Version**
GN=2.12.0

**Description du bug**
Lorsque je me connecte à l'application avec certains utilisateurs, l'application ne parvient pas à récupérer les jeux de données. 
J'obtiens une Erreur 500 sur la requête POST api `geonature/api/meta/datasets?orderby=dataset_name`.

![image](https://user-images.githubusercontent.com/96542451/229725946-fe0f4c62-0af7-4f8b-9c76-9749927e1ebf.png)

Modules concernés : 
- Occtax
- Occhab
- Import
- Synthèse
- Validation

**Comportement attendue**
Récupérer la liste des JDDs disponibles pour l’utilisateur.

**Comment reproduire**
Il semble que les utilisateurs posant problème sont liés à des groupes que j'ai défini dont
- le profil est `Référent` (code 3)
- Avec/Sans `permissions de Sensibilité` sur le module GeoNature

Pour autant, je ne vois pas en quoi se profil serait plus bloquant qu'un autre. 

**Logs**
``` py
[2023-04-04 09:43:19 +0200] [2504] [ERROR] Exception on /meta/datasets [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 18, in decorated_view
    return view_func(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_meta/routes.py", line 155, in get_datasets
    return dataset_schema.jsonify(query.all(), many=True)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask_marshmallow/schema.py", line 39, in jsonify
    data = self.dump(obj, many=many)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 557, in dump
    result = self._serialize(processed_obj, many=many)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 519, in _serialize
    return [
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 520, in <listcomp>
    self._serialize(d, many=False)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 525, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/fields.py", line 342, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/marshmallow/fields.py", line 1911, in _serialize
    return self._serialize_method(obj)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/schema.py", line 22, in get_cruved
    return {action: obj.has_instance_permission(scope) for action, scope in scopes.items()}
  File "/home/geonatureadmin/geonature/backend/geonature/utils/schema.py", line 22, in <dictcomp>
    return {action: obj.has_instance_permission(scope) for action, scope in scopes.items()}
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_meta/models.py", line 529, in has_instance_permission
    if g.current_user == self.digitizer or g.current_user in self.user_actors:
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 728, in get
    value = callable_(state, passive)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 969, in __call__
    return strategy._load_for_state(state, passive)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 710, in _load_for_state
    self._invoke_raise_load(state, passive, "raise")
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 671, in _invoke_raise_load
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: 'TDatasets.digitizer' is not available due to lazy='raise'
```
Il semble que les logs orientent l'origine du problème vers la lecture de l'objet `scopes` après la récupération du CRUVED.

**Comment by cen-cgeier** [comment]
Sur mon instance, il semble que l'erreur survient lorsque le `CRUVED` du module `METADATA` n'est pas hérité du module GéoNature et qu'une des lettres a une valeur différente de 3.

**Comment by jbrieuclp** [comment]
La même chez moi, c'est le fait de forcer le raisedLoad('*') ici qui cause le problème : https://github.com/PnX-SI/GeoNature/blob/5999efb11113081f1f9e8c65d44130318069c7b6/backend/geonature/core/gn_meta/routes.py#L126 

Avec ce raisedLoad, digitizer n'est pas chargé (pas de jointure en SQL) et donc la vérif ici crash :
https://github.com/PnX-SI/GeoNature/blob/5999efb11113081f1f9e8c65d44130318069c7b6/backend/geonature/core/gn_meta/models.py#L522-L537

Il y a le même crash ici où acquisition_framework n'est pas non plus chargé :
https://github.com/PnX-SI/GeoNature/blob/5999efb11113081f1f9e8c65d44130318069c7b6/backend/geonature/core/gn_meta/models.py#L533


Le truc c'est que sans le raisedLoad la requête est bien longue.

**Comment by jbrieuclp** [comment]
On peut rapprocher ce problème du #2444 
Il nous faut les infos du digitizer et des CA pour la gestion des droits au niveau de cette fonction 
https://github.com/PnX-SI/GeoNature/blob/5999efb11113081f1f9e8c65d44130318069c7b6/backend/geonature/core/gn_meta/models.py#L522-L537

Sans ça selon les niveau de droits ça crash.

Du coup en modifiant ça :
https://github.com/PnX-SI/GeoNature/blob/5999efb11113081f1f9e8c65d44130318069c7b6/backend/geonature/core/gn_meta/routes.py#L125-L130
Par ça on force le chargement de ces FK qui étaient oubliées :
```
    query = query.options(
        Load(TDatasets).raiseload("*"),
        joinedload("cor_dataset_actor").options(
            joinedload("role"),
            joinedload("organism"),
        ),
        joinedload("digitizer"),
        joinedload("acquisition_framework")
    )
```

Plus bas il faut aussi réadapter ça :
https://github.com/PnX-SI/GeoNature/blob/5999efb11113081f1f9e8c65d44130318069c7b6/backend/geonature/core/gn_meta/routes.py#L144-L146
Par ça pour ne pas charger 2 fois le digitizer :
```
if "modules" in fields:
        query = query.options(joinedload("modules"))
        only.append("modules")
```

**Comment by bouttier** [comment]
Corrigé dans #2463
