### ISSUE TITLE
[2.12.2] Pas de récupération du référentiel de sensibilité Taxref 14

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#2519]
J'essaye de récupérer le référentiel de sensibilité pour Taxref 14, avec la commande :
```
geonature sensitivity add-referential \
        --source-name "Référentiel sensibilité TAXREF v14 20220331" \
        --url https://inpn.mnhn.fr/docs-web/docs/download/401876 \
        --zipfile RefSensibiliteV14_20220331.zip \
        --csvfile RefSensibilite_V14_31032022/RefSensibilite_14.csv  \
        --encoding=iso-8859-15
```

Cela ne fonctionne pas, et j'ai ce retour :

```
Created temporary directory '/tmp/tmp4r_lf_hi'
Downloading 'RefSensibiliteV14_20220331.zip'…
Ajout de règles de sensibilité 'Référentiel sensibilité TAXREF v14 20220331'
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/sensitivity/routes.py", line 104, in add_referential
    count = insert_sensitivity_referential(source_name, csvfile)
  File "/home/geonatureadmin/geonature/backend/geonature/core/sensitivity/utils.py", line 78, in insert_sensitivity_referential
    criteria = get_nomenclature("STATUT_BIO", code=row["STATUT_BIOLOGIQUE"])
  File "/home/geonatureadmin/geonature/backend/geonature/core/sensitivity/utils.py", line 21, in get_nomenclature
    return Nomenclature.query.filter(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

```
Est-ce que quelqu'un saurait d'où vient le problème ?
Merci d'avance !

**Comment by joelclems** [comment]
C'est bizarre c'est comme s'il te manquait des nomenclatures

Je crois qu'il n'y que les valeurs NULL, 3,4, 7 pour la colonne `STATUT_BIOLOGIQUE`


que te donnes la requete sql suivante ?
```
SELECT bnt.mnemonique, CD_NOMENCLATURE FROM REF_NOMENCLATURES.T_NOMENCLATURES TN 
JOIN REF_NOMENCLATURES.BIB_NOMENCLATURES_TYPES BNT ON TN.ID_TYPE  = BNT.ID_TYPE 
WHERE bnt.MNEMONIQUE = 'STATUT_BIO' OR bnt.MNEMONIQUE = 'OCC_COMPORTEMENT'
ORDER BY bnt.MNEMONIQUE, CD_NOMENCLATURE:: int 
```

**Comment by joelclems** [comment]
Il faudrait peut être vérifier si dans la liste  tu n'as pas de nomenclature désactivée qui pourrait poser soucis

**Comment by Splendens** [comment]
C'était bien ça ! En réactivant les nomenclatures désactivées pour _statut biologique_ et _comportement_, la récupération du référentiel de sensibilité fonctionne sans problème.
Merci beaucoup pour ton aide !
