### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2538]
**Version**
GeoNature 2.11.1

**Description du bug**
La commande `/home/gnadmin/geonature/backend/venv/bin/geonature profiles update` retourne une erreur postgis sur la fonction pgis_geometry_union_finalfn qui est dépréciée depuis postgis 3.3.0. Voir les logs de l'erreur retournée par la console.
**Lancer `SELECT postgis_extensions_upgrade();` permet de résoudre le problème**. Mais je ne sais pas s'il y a lieu de revoir le code pour utiliser une fonction non dépréciée.

**Comportement attendue**
Permettre le rafraichiseement des profiles avec une version récente de postgis.

**Comment reproduire**
Lancer l'update des profiles sur une instance avec postgis en version 3.3.2.

**Logs**
```
/home/gnadmin/geonature/backend/venv/bin/geonature profiles update
Traceback (most recent call last):
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.FeatureNotSupported: ERREUR:  A stored procedure tried to use deprecated C function 'pgis_geometry_union_finalfn'
DETAIL:  Library function 'pgis_geometry_union_finalfn' was deprecated in PostGIS 3.3.0
HINT:  Consider running: SELECT postgis_extensions_upgrade()
CONTEXT:  instruction SQL « REFRESH MATERIALIZED VIEW CONCURRENTLY gn_profiles.vm_valid_profiles »
fonction PL/pgSQL gn_profiles.refresh_profiles(), ligne 5 à instruction SQL


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gnadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gnadmin/geonature/backend/geonature/core/gn_profiles/routes.py", line 260, in update
    DB.session.execute(func.gn_profiles.refresh_profiles())
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1296, in execute
    clause, params or {}
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/sql/functions.py", line 158, in _execute_on_connection
    return connection._execute_function(self, multiparams, params)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1016, in _execute_function
    return self._execute_clauseelement(func.select(), multiparams, params)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/gnadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.NotSupportedError: (psycopg2.errors.FeatureNotSupported) ERREUR:  A stored procedure tried to use deprecated C function 'pgis_geometry_union_finalfn'
DETAIL:  Library function 'pgis_geometry_union_finalfn' was deprecated in PostGIS 3.3.0
HINT:  Consider running: SELECT postgis_extensions_upgrade()
CONTEXT:  instruction SQL « REFRESH MATERIALIZED VIEW CONCURRENTLY gn_profiles.vm_valid_profiles »
fonction PL/pgSQL gn_profiles.refresh_profiles(), ligne 5 à instruction SQL

[SQL: SELECT gn_profiles.refresh_profiles() AS refresh_profiles_1]
(Background on this error at: http://sqlalche.me/e/13/tw8g)
```

**Comment by camillemonchicourt** [comment]
OK, on n'a pas rencontré le soucis, certainement car on n'a pas la même version de PostGIS.

**Comment by lpofredc** [comment]
En effet, j'ai déjà rencontré ce type de problèmes lié à une différence de version entre l'extension activée dans la bdd et les librairies installées sur le serveur. cette fonction `postgis_extensions_upgrade()` permet justement de mettre à niveau l'extension de la bdd en fonction de la version installée sur le serveur via le gestionnaire de paquets. 

Ce n'est pas lié à GeoNature, mais un pb d'administrateur système.
