### ISSUE TITLE
[Geonature 2.12.3] Installation bloquée au niveau des npm

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/GeoNature#2633]
Bonjour à tous,

J'ai résolu le problème venant de la plateforme Plesk avec Nginx en conflit avec Apache. J'ai un serveur tout neuf.
Mais je n'arrive toujours pas à faire l'installation de Geonature. Des messages d'erreurs se répètent en boucle : 
`npm WARN old lockfile FetchError: request to https://registry.npmjs.org/angular-filter failed, reason: connect ETIMEDOUT 2606:4700::6810:1823:443
npm WARN old lockfile     at ClientRequest.<anonymous> (/home/geonatureadmin/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm WARN old lockfile     at ClientRequest.emit (node:events:513:28)
npm WARN old lockfile     at TLSSocket.socketErrorListener (node:_http_client:502:9)
npm WARN old lockfile     at TLSSocket.emit (node:events:525:35)
npm WARN old lockfile     at emitErrorNT (node:internal/streams/destroy:151:8)
npm WARN old lockfile     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm WARN old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm WARN old lockfile  Could not fetch metadata for angular-filter@0.5.17 FetchError: request to https://registry.npmjs.org/angular-filter failed, reason: connect ETIMEDOUT 2606:4700::6810:1823:443
npm WARN old lockfile     at ClientRequest.<anonymous> (/home/geonatureadmin/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm WARN old lockfile     at ClientRequest.emit (node:events:513:28)
npm WARN old lockfile     at TLSSocket.socketErrorListener (node:_http_client:502:9)
npm WARN old lockfile     at TLSSocket.emit (node:events:525:35)
npm WARN old lockfile     at emitErrorNT (node:internal/streams/destroy:151:8)
npm WARN old lockfile     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm WARN old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm WARN old lockfile   code: 'ETIMEDOUT',
npm WARN old lockfile   errno: 'ETIMEDOUT',
npm WARN old lockfile   syscall: 'connect',
npm WARN old lockfile   address: '2606:4700::6810:1823',
npm WARN old lockfile   port: 443,
npm WARN old lockfile   type: 'system'
npm WARN old lockfile }
`

J'ai lu ce post qui parle du même problème [https://github.com/PnX-SI/GeoNature/issues/1077](url)

mais je ne comprends pas comment le résoudre : 

> J'ai relancé l'installation à partir d'un snapshot (avec virtualbox) avec un --verbose sur la ligne npm ci --only=prod

est-ce que vous pourriez me décrire la procédure en mode "débutant" ?

Sinon si c'est un problème temporaire d'accès au site des paquets, je peux retenter plus tard mais ça 2 jours que j'essaie et le blocage se fait toujours au même endroit. Je mets le log en pj.

Merci d'avance pour votre aide et bonne journée,
Vottana

[install_all.log](https://github.com/PnX-SI/GeoNature/files/12080278/install_all.log)

**Comment by Vottana** [comment]
Avec l'aide de @MoulinZ et intervention de l'hébergeur, le problème était lié à mon serveur qui n'avait pas accès à Internet.
Explication de l'hébergeur : 
> le système Debian par défaut chercher à joindre internet via l'IPV6 sauf que le serveur ne dispose pas d'IPV6.
J'ai donc désactivé l'ip V6 et le ping de google fonctionne bien.

Je lance la 5e tentative d'installation. Je fermerai l'issue ensuite, si tout va bien.
