### ISSUE TITLE
[CONFIG] Erreur de mise à jour  après modification de geonature_config.toml

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/GeoNature#2675]
**Version Geonature 2.11.1**

J'ai modifié la section `[MAPCONFIG]` du fichier **geonature_config.toml** comme suit 
Objectif : zoomer sur la Normandie + ajouter les couches de ref_geo (espaces naturels protégés)

A priori geonature n'accepte pas de zoomer sur le centre de la Normandie (j'ai aussi modifié le niveau de zoom par défaut).

```
31 # Configuration cartographique
32 [MAPCONFIG]
33 
34    # Coordonnées par défaut du centre de la carte à afficher
35    # Attention : les coordonnées sont au format [Y, X]
36    # Cf Leaflet configuration (https://leafletjs.com/reference-1.4.0.html#latlng-l-latlng)
37    CENTER = [49.12118016573089, 0.10697812360]
38
39	# Zoom par défaut
40    ZOOM_LEVEL = 10
41	
42    # Zoom à partir duquel on peut pointer un relevé
43    ZOOM_LEVEL_RELEVE = 15
44
45    # Zoom appliqué sur la carte lors du clic sur une liste
46    ZOOM_ON_CLICK = 16
47
48    # activation d'un boutton de géolocalisation sur la carte
49    GEOLOCATION = true
50
51    # Restreindre la recherche OpenStreetMap (sur la carte dans l'encart "Rechercher un lieu")
52    # à certains pays. Les pays doivent être au format ISO_3166-1 :
53    # https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 et séparés par une virgule.
54    # Exemple : OSM_RESTRICT_COUNTRY_CODES = "fr,es,be,ch" (Restreint à France, Espagne, Belgique
55    # et Suisse)
56    # Laisser à null pour n'avoir aucune restriction OSM_RESTRICT_COUNTRY_CODES = null
57    OSM_RESTRICT_COUNTRY_CODES = 'fr,es,be,ch'
58
59 # Liste des fonds de carte proposés sur les cartes de GeoNature
60 # chaque section [[MAPCONFIG.BASEMAP]] définit un fond de carte
61 # l'option service est obligatoire uniquement pour les wms
62 # l'ensemble des paramètre WMS peuvent être passé dans cette section
63 [[MAPCONFIG.BASEMAP]]
64    name = 'OpenstreetMap'
65    url = '//{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'
66    attribution = 'OSM contributors'
67	
68 # Add base layers on maps (from ref_geo, WMS, WFS, GeoJSON...)
69 [[MAPCONFIG.REF_LAYERS]]
70    code = 'SCEN'
71    label = 'Terrain acquis par le CEN Normandie'
72    type = 'area'
73    activate = false
74    style = { color = 'grey', fill = false, fillOpacity = '0.0', weight = 2 }
75    params = {limit = 2000}
```

Lors de la mise à jour de la configuration, j'ai cette erreur : 
```
(venv) root@Geonature:/home/geonatureadmin/geonature/backend# geonature update_configuration
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/geonature/utils/config.py", line 35, in <module>
    config_frontend = GnGeneralSchemaConf().load(config_toml, unknown=EXCLUDE)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'MAPCONFIG': {'GEOLOCATION': ['Unknown field.']}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 5, in <module>
    from geonature.core.command import main
  File "/home/geonatureadmin/geonature/backend/geonature/__init__.py", line 1, in <module>
    from .app import create_app
  File "/home/geonatureadmin/geonature/backend/geonature/app.py", line 21, in <module>
    from geonature.utils.config import config
  File "/home/geonatureadmin/geonature/backend/geonature/utils/config.py", line 37, in <module>
    raise ConfigError(CONFIG_FILE, e.messages)
geonature.utils.errors.ConfigError: Error in the config file '/home/geonatureadmin/geonature/config/geonature_config.toml'. Fix the following:

        MAPCONFIG:
                - {'GEOLOCATION': ['Unknown field.']}
```

Sachant que j'ai déjà dû modifier la ligne ` OSM_RESTRICT_COUNTRY_CODES = 'fr,es,be,ch'` car il n'acceptait pas la valeur nulle. Je mets l'erreur pour info :

```
(venv) root@Geonature:/home/geonatureadmin/geonature/backend# geonature update_configuration
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 918, in load_value
    v = int(v, 0)
ValueError: invalid literal for int() with base 0: 'null'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 5, in <module>
    from geonature.core.command import main
  File "/home/geonatureadmin/geonature/backend/geonature/__init__.py", line 1, in <module>
    from .app import create_app
  File "/home/geonatureadmin/geonature/backend/geonature/app.py", line 21, in <module>
    from geonature.utils.config import config
  File "/home/geonatureadmin/geonature/backend/geonature/utils/config.py", line 29, in <module>
    config_toml = load_toml(CONFIG_FILE) if CONFIG_FILE else {}
  File "/home/geonatureadmin/geonature/backend/geonature/utils/utilstoml.py", line 32, in load_toml
    return toml.load(str(toml_file))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: invalid literal for int() with base 0: 'null' (line 57 column 1 char 2089)

```

**Comment by camillemonchicourt** [comment]
Salut, OK, là je comprends pas le soucis, mais ton fichier de configuration doit avoir un problème.
Là il semble avoir un soucis avec `GEOLOCATION` qu'il dit ne pas connaitre, je vois pas pourquoi.
Ou sinon le soucis vient du paramètre suivant `OSM_RESTRICT_COUNTRY_CODES`.

Mais dans tous les cas, dans le fichier `geonature_config.toml`, tu ne dois inclure que les paramètres dont tu veux modifier la valeur par défaut. Donc il ne faut surtout pas remettre tous les paramètres. Donc tu ne dois pas remettre `OSM_RESTRICT_COUNTRY_CODES` dans ce fichier, ni tous les autres paramètres que tu ne souhaites pas modifier, mais seulement surcoucher ceux dont tu veux modifier la valeur fournie par défaut.

Peux-tu supprimer le paramètre `OSM_RESTRICT_COUNTRY_CODES` et tous les autres paramètres que tu ne veux pas modifier, et nous dire si tu as toujours le même soucis et les logs associés ?

**Comment by marie-laure-cen** [comment]
ça fonctionne en effet en enlevant les lignes en trop : 
```
#############################################
# GeoNature backend global configuration file
#############################################

# Database
SQLALCHEMY_DATABASE_URI = "postgresql://geonatadmin:CENN2022!@localhost:5432/geonature2db?application_name=geonature"
URL_APPLICATION = 'http://geonature.cenwms.xyz/geonature'
API_ENDPOINT = 'http://geonature.cenwms.xyz/geonature/api'
API_TAXHUB = 'http://geonature.cenwms.xyz/taxhub/api'

# Application

# Nom de l'application dans la page d'accueil.
appName = "CEN Normandie - GeoNature 2"

# Remplacer par une clé alétoire complexe
SECRET_KEY = '52a6e036fcb197831fdb45e94de633bf39ecd37ba711fca4aab47c407eac9cf8'

# Langue principale par défaut
DEFAULT_LANGUAGE='fr'

# MTD (pour la connexion au webservice de métadonnées de l'INPN)
XML_NAMESPACE = "{http://inpn.mnhn.fr/mtd}"
MTD_API_ENDPOINT = "https://preprod-inpn.mnhn.fr/mtd"

#######################################################################################
###### Si vous souhaitez surcoucher certains paramètres,
###### compléter les sections ci-dessous à partir du modèle default_config.toml.example
#######################################################################################

# Configuration liée aux ID de BDD
[BDD]

# Configuration générale du frontend
[FRONTEND]

# Configuration de la Synthese
[SYNTHESE]

# Configuration cartographique
[MAPCONFIG]

    # Coordonnées par défaut du centre de la carte à afficher
    # Attention : les coordonnées sont au format [Y, X]
    # Cf Leaflet configuration (https://leafletjs.com/reference-1.4.0.html#latlng-l-latlng)
    CENTER = [49.12118016573089, 0.10697812360]

	# Zoom par défaut
    ZOOM_LEVEL = 10
	
# Add base layers on maps (from ref_geo, WMS, WFS, GeoJSON...)
[[MAPCONFIG.REF_LAYERS]]
    code = 'SCEN'
    label = 'Terrain acquis par le CEN Normandie'
    type = 'area'
    activate = false
    style = { color = 'grey', fill = false, fillOpacity = '0.0', weight = 2 }
    params = {limit = 2000}

# Configuration médias
[MEDIAS]

[ALEMBIC]
VERSION_LOCATIONS = '/home/geonatureadmin/usershub/app/migrations/versions/'
```

par contre j'ai une nouvelle erreur plus tard :

```
(venv) root@Geonature:/home/geonatureadmin/geonature/backend# geonature update_configuration
Génération de la configuration du frontend :
  GeoNature … OK
  Module OCCTAX … OK
  Module OCCHAB … OK
  Module VALIDATION … OK
Rebuild du frontend …
bash: nvm : commande introuvable
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/main.py", line 132, in update_configuration
    build_frontend()
  File "/home/geonatureadmin/geonature/backend/geonature/utils/command.py", line 68, in build_frontend
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/bash', '-i', '-c', 'nvm exec npm run build']' returned non-zero exit status 127.
```

**Comment by camillemonchicourt** [comment]
Attention, il ne faut surcoucher que les paramètres à modifier.

Donc il ne faut pas non plus avoir dans votre fichier de conf : 

```
# Langue principale par défaut
DEFAULT_LANGUAGE='fr'
```

```
# MTD (pour la connexion au webservice de métadonnées de l'INPN)
XML_NAMESPACE = "{http://inpn.mnhn.fr/mtd}"
MTD_API_ENDPOINT = "https://preprod-inpn.mnhn.fr/mtd"
```

```
[ALEMBIC]
VERSION_LOCATIONS = '/home/geonatureadmin/usershub/app/migrations/versions/'
```

**Comment by camillemonchicourt** [comment]
Pour ton message d'erreur, tu as un soucis au niveau du rebuild du frontend, je ne sais pas pourquoi il ne trouve pas `nvm`.
Mais tout ça a évolué en 2.12 où il n'est plus nécessaire de relancer la commande `geonature update_configuration` après chaque modification de la configuration.

Donc le mieux serait de passer en 2.12 (voire 2.13 ;-).

Mais en attendant tu peux tenter ça, en allant dans le dossier frontend de GeoNature et en lançant la commande de rebuild du frontend : 

```
cd ~/geonature/frontend
nvm use
npm run build
```

**Comment by mvergez** [comment]
Bonjour,

Attention : `nvm` pas `nvw`.

La commande `npm` sera rendue disponible par `nvm use`

**Comment by camillemonchicourt** [comment]
C'est car c'est `nvm use`, pas `nvw use`.
Il faut toujours copier/coller. :-)

Et attention aussi, il ne faut pas travailler avec l'utilisateur `root`. Je vois que vous avez lancé les commandes avec cet utilisateur, il ne faut pas.
Cela va poser de gros soucis. Ce sera l'utilisateur `root` qui sera propriétaire et aura des droits sur les fichiers, et de ce fait l'utilisateur utilisé par l'application (`geonatadmin`) n'aura pas accès à ces fichiers et l'application ne fonctionnera pas.

Votre problème est peut-être lié. D'ailleurs si vous avez travaillé depuis un moment avec l'utilisateur `root`, vous aurez certainement différents soucis.

**Comment by marie-laure-cen** [comment]
Mon programme qui permet de lancer des commandes linux sur windows n'accepte pas le copier coller 😅​

```
(venv) root@Geonature:/home/geonatureadmin/geonature/frontend# nvm list
-bash: nvm : commande introuvable
(venv) root@Geonature:/home/geonatureadmin/geonature/frontend# nvm use
-bash: nvm : commande introuvable
```

**Comment by marie-laure-cen** [comment]
ok merci je vais essayer en changeant d'utilisateur 
Pour l'instant avec  root la commande nvm use est introuvable (je n'avais pas lu le message jusqu'au bout). 
Malheureusement mon programme de ligne de commande linux sous windows n'accepte pas le copier/coller ​😅​

**Comment by marie-laure-cen** [comment]
En effet, en passant par l'utilisateur geonatureadmin ça fonctionne ! merci pour vos réponses

**Comment by camillemonchicourt** [comment]
OK donc c'était le soucis était bien celui-ci. J'espère que le fait d'avoir utilisé l'utilisateur `root` n'aura pas d'autres effets de bord.

Je ne sais pas si le soucis initial du fichier de configuration était aussi lié à l'utilisateur de l'utilisateur `root` car je comprends pas pourquoi il y a eu un soucis, mais tant mieux si c'est OK désormais avec du ménage dans le fichier de configuration.

**Comment by SamyM71** [comment]
Bonjour,


> Malheureusement mon programme de ligne de commande linux sous windows 
> n'accepte pas le copier/coller ​😅​


Pour info le PowerShell de Windows permet de se connecter facilement en 
SSH à un serveur Linux et il accepte les copier-coller (clic droit il me 
semble).
