### ISSUE TITLE
[Dashboard] Erreur 500 sur le module Dashboard

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/GeoNature#2683]
Version GN 2.12.3, Dashboard 1.4.0

Bonjour à tous,
J'ai essayé d'installer le module Dashboard. Je n'ai eu aucun message d'erreur lors de l'installation, mais fausse joie. J'ai plein d'erreur 500 Internal server error lorsque je vais sur le module. Tous les autres modules fonctionnent bien.

![image](https://github.com/PnX-SI/GeoNature/assets/15034095/4cf758b0-ab8b-4a15-a4cc-7be72f886907)

Dans la base geonature2db, je n'ai pas de schéma gn_dashboard, mais j'ai bien le dossier home/geonature/gn_module_dashboard

Je n'ai pas l'impression d'avoir loupé une étape dans l'installation mais le module n'a clairement pas bien été installé. Vous pouvez m'aidez à rattraper le truc ? J'ai fait l'installation 2 fois et même constat.

Merci d'avance pour votre aide !
Vottana

**Comment by camillemonchicourt** [comment]
Il nous faudrait les logs de GeoNature dans /var/logs/geonature/geonature.log

Et enventuellement tous les messages du terminal lors de l'installation du module.

Tu as bien redémarré le service GeoNature après installation du module ?

**Comment by Vottana** [comment]
Bonjour Camille, 

Voici les messages du terminal à partir de l'installation :
et le log en pj.
J'ai bien fait le `sudo restart systemctl geonature`
Merci !
```
geonatureadmin@ns307:~$ source ~/geonature/backend/venv/bin/activate
(venv) geonatureadm
[geonature.log](https://github.com/PnX-SI/GeoNature/files/12511602/geonature.log)
in@ns307:~$ geonature install-gn-module ~/gn_module_dashboard DASHBOARD
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1841: SAWarning: Property TBaseVisits.dataset on mapped class TBaseVisits->t_base_visits being replaced with new property TBaseVisits.dataset; the old property will be discarded
  util.warn(
Installation du backend…
Obtaining file:///home/geonatureadmin/gn_module_dashboard
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: gn-module-dashboard
  Building editable for gn-module-dashboard (pyproject.toml) ... done
  Created wheel for gn-module-dashboard: filename=gn_module_dashboard-1.4.0-0.editable-py3-none-any.whl size=16101 sha256=c2bdbd5746a733f4bec31dbabae83c22fc5c286bfbbca266e576a16861e93a00
  Stored in directory: /tmp/pip-ephem-wheel-cache-jxwt8jwf/wheels/f2/87/86/8a04233135bb705e43245a637754d4e9970b8da09ba977979f
Successfully built gn-module-dashboard
Installing collected packages: gn-module-dashboard
  Attempting uninstall: gn-module-dashboard
    Found existing installation: gn-module-dashboard 1.4.0
    Uninstalling gn-module-dashboard-1.4.0:
      Successfully uninstalled gn-module-dashboard-1.4.0
Successfully installed gn-module-dashboard-1.4.0

[notice] A new release of pip is available: 23.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Correction du lien symbolique /home/geonatureadmin/geonature/frontend/external_modules/dashboard → /home/geonatureadmin/gn_module_dashboard/frontend
Installation des dépendances frontend…
Running node v16.20.1 (npm v8.19.4)

up to date, audited 1 package in 611ms

found 0 vulnerabilities
Création de la configuration frontend…
Rebuild du frontend …
Found '/home/geonatureadmin/geonature/frontend/.nvmrc' with version <lts/gallium>
Running node v16.20.1 (npm v8.19.4)

> geonature@0.0.0 build
> ng build

✔ Browser application bundle generation complete.
✔ Copying assets complete.
⠋ Generating index html...1 rules skipped due to selector errors:
  .custom-file-input:lang(en)~.custom-file-label -> unmatched pseudo-class :lang
✔ Index html generation complete.

Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.3b5c23f3b189d56f.js      | main          |   2.29 MB |               499.61 kB
styles.884e8b65c143adb9.css   | styles        | 331.92 kB |                40.89 kB
scripts.389cfc411fcb8b0c.js   | scripts       | 248.96 kB |                55.97 kB
polyfills.25e6f5a201d9f0da.js | polyfills     |  67.25 kB |                20.75 kB
runtime.dbb0652270c00413.js   | runtime       |   3.17 kB |                 1.53 kB

                              | Initial Total |   2.93 MB |               618.75 kB

Lazy Chunk Files              | Names         |  Raw Size | Estimated Transfer Size
301.2ba2e2fdd2ad4684.js       | -             | 443.29 kB |                75.43 kB
266.3e689edf62886ef7.js       | -             | 377.24 kB |                61.77 kB
134.0b06b5596850e32a.js       | -             | 280.86 kB |                57.08 kB
453.5c57a92c300c7d66.js       | -             | 210.70 kB |                34.48 kB
metadata.ccbacf9cd95c0d85.js  | metadata      | 118.67 kB |                22.36 kB
614.e381b340cfcfabee.js       | -             | 114.49 kB |                19.96 kB
313.3997dbdfff0ec3d3.js       | -             |  99.82 kB |                21.54 kB
242.3a365c3e3f417047.js       | -             |  54.15 kB |                12.22 kB
synthese.902b3d7544798053.js  | synthese      |  48.96 kB |                13.62 kB
97.9b036ca7f43e6bae.js        | -             |  37.51 kB |                 9.37 kB
274.960596ca809bb545.js       | -             |  13.68 kB |                 5.12 kB
user.dd7f3bc2c44b9636.js      | user          |   9.02 kB |                 2.43 kB
common.7d3ee64a5bf7e139.js    | common        |   5.33 kB |                 1.97 kB
admin.65987f6a8396fd6c.js     | admin         |   2.40 kB |               987 bytes

Build at: 2023-09-04T08:04:04.020Z - Hash: 1420e5ebb975a2bf - Time: 133688ms

Warning: /home/geonatureadmin/geonature/frontend/external_modules/dashboard/app/module.config.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/external_modules/monitorings/app/components/monitoring-properties/monitoring-properties.component.ts depends on 'html2canvas'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/external_modules/monitorings/app/module.config.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/external_modules/occhab/app/components/occhab-map-list/occhab-map-list.component.ts depends on 'moment'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/external_modules/occhab/app/module.config.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/external_modules/occtax/app/module.config.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/external_modules/occtax/app/occtax-map-list/occtax-map-list.component.ts depends on 'moment'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/external_modules/validation/app/module.config.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/src/app/GN2CommonModule/form/autocomplete/autocomplete.component.ts depends on 'rxjs/observable/of'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/app/GN2CommonModule/form/dynamic-form-generator/dynamic-form-generator.component.ts depends on 'fast-deep-equal/es6'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/app/GN2CommonModule/map/map.service.ts depends on 'leaflet.markercluster'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/app/GN2CommonModule/map/map.service.ts depends on 'lodash'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/app/app.module.ts depends on 'ng2-cookies'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/app/components/home-content/home-content.component.ts depends on 'leaflet'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/app/metadataModule/services/metadata-search-form.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/src/app/syntheseModule/services/form.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-info-obs/modal-info-obs.component.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: /home/geonatureadmin/geonature/frontend/src/app/syntheseModule/synthese.component.ts depends on 'lodash/cloneDeep'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/geonatureadmin/geonature/frontend/src/conf/app.config.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.


Rebuild du frontend terminé.
Installation / mise à jour de la base de données…
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 86, in install_gn_module
    if not module_db_upgrade(module_dist, x_arg=x_arg):
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 127, in module_db_upgrade
    elif alembic_branch and not alembic_branch_in_use(alembic_branch, directory, x_arg):
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 79, in alembic_branch_in_use
    base_revision = script.get_revision(script.as_revision_number(branch_name))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/base.py", line 324, in as_revision_number
    rev, branch_name = self.revision_map._resolve_revision_number(id_)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/revision.py", line 753, in _resolve_revision_number
    self._revision_map
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/revision.py", line 218, in _revision_map
    self._add_depends_on(all_revisions, cast(_RevisionMapType, map_))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/revision.py", line 360, in _add_depends_on
    deps = [
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/revision.py", line 361, in <listcomp>
    map_[dep] for dep in util.to_tuple(revision.dependencies)
KeyError: 'f051b88a57fd'
(venv) geonatureadmin@ns307:~$ deactivate
geonatureadmin@ns307:~$ sudo systemctl restart geonature
[sudo] Mot de passe de geonatureadmin :
geonatureadmin@ns307:~$
```

**Comment by Vottana** [comment]
@SamyM71 me fait remarqué qu'il y a certainement un problème de compatibilité de version. Je n'avais pas vu que la 2.13 de Gn était sortie. J'ai pris la dernière version de Dashboard. Je vais tenter l'installation avec la version précédente.

**Comment by camillemonchicourt** [comment]
Ah oui les migrations ne sont pas passées. Y a bien des erreurs dans les messages d'installation

**Comment by Vottana** [comment]
Merci ! Je n'ai pas fait attention aux messages d'erreurs, je serais plus attentive sur les compatibilités de version.
Concernant l'installation de la 2.13, je dois avouer que j'ai un peu peur de repartir sur une installation de GN. J'ai tellement galéré à avoir une instance qui tourne sans message d'erreur. Je vais attendre que les collègues partenaires se lancent dedans :)
Bonne journée.
