### ISSUE TITLE
Migration 2.12.3 to 2.13.1 manque la table l_linears

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#2707]
**Migration de la version 2.12.3 to 2.13.1**

**Description du bug**
Une erreur d'installation de la bdd ressort pour la table ref_geo.l_linears

    Mise à jour de la base de données…
    /home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1841: SAWarning: Property TBaseVisits.dataset on mapped class TBaseVisits->t_base_visits being replaced with new property TBaseVisits.dataset; the old property will be discarded
      util.warn(
    /home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1841: SAWarning: Property TBaseVisits.dataset on mapped class TBaseVisits->t_base_visits being replaced with new property TBaseVisits.dataset; the old property will be discarded
      util.warn(
    INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
    INFO  [alembic.runtime.migration] Will assume transactional DDL.
    /home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1841: SAWarning: Property TBaseVisits.dataset on mapped class TBaseVisits->t_base_visits being replaced with new property TBaseVisits.dataset; the old property will be discarded
      util.warn(
    Context impl PostgresqlImpl.
    Will assume transactional DDL.
    INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
    INFO  [alembic.runtime.migration] Will assume transactional DDL.
    INFO  [alembic.runtime.migration] Running upgrade e2a94808cf76 -> 95acee9f0452, add comment notification
    INFO  [alembic.runtime.migration] Running upgrade 95acee9f0452 -> df5a5099e084, add additional fields object
    INFO  [alembic.runtime.migration] Running upgrade df5a5099e084 -> 0630b93bcfe0, add permissions inherited modules objects
    INFO  [alembic.runtime.migration] Running upgrade 0630b93bcfe0 -> 7fe46b0e4729, multiple filters per permission
    INFO  [alembic.runtime.migration] Running upgrade 7fe46b0e4729 -> f051b88a57fd, permissions available
    INFO  [alembic.runtime.migration] Running upgrade 488a2eeee4be -> cef2c2d66eb2, declare available permissions
    INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
    INFO  [alembic.runtime.migration] Will assume transactional DDL.
    INFO  [alembic.runtime.migration] Running upgrade 1b4f44762020 -> e170d1902137, declare permissions
    INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
    INFO  [alembic.runtime.migration] Will assume transactional DDL.
    INFO  [alembic.runtime.migration] Running upgrade e78003460441 -> fc90d31c677f, declare available permissions
    INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
    INFO  [alembic.runtime.migration] Will assume transactional DDL.
    INFO  [alembic.runtime.migration] Running upgrade 112ccf1024ce -> f4bf21ac6238, fix temp user organism size
    INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
    INFO  [alembic.runtime.migration] Will assume transactional DDL.
    INFO  [alembic.runtime.migration] Running upgrade f7374cd6e38d -> dea1645de8c0, Référentiel point, cor (area, linear, point)
    INFO  [alembic.runtime.migration] Running upgrade dea1645de8c0 -> 795f6ea8ec45, cor_areas & cor_linear_areas
    Traceback (most recent call last):
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
        self.dialect.do_execute(
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
        cursor.execute(statement, parameters)
    psycopg2.errors.UndefinedTable: ERREUR:  la relation « ref_geo.l_linears » n'existe pas

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
        sys.exit(main())
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
        rv = self.invoke(ctx)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
        return __callback(*args, **kwargs)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
        return __ctx.invoke(f, *args, **kwargs)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
        return __callback(*args, **kwargs)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/utils_flask_sqla/commands.py", line 100, in autoupgrade
        flask_migrate.upgrade(directory, revision, sql, tag, x_arg)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_migrate/__init__.py", line 111, in wrapped
        f(*args, **kwargs)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_migrate/__init__.py", line 200, in upgrade
        command.upgrade(config, revision, sql=sql, tag=tag)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/command.py", line 399, in upgrade
        script.run_env()
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/base.py", line 578, in run_env
        util.load_python_file(self.dir, "env.py")
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
        module = load_module_py(module_id, path)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
        spec.loader.exec_module(module)  # type: ignore
      File "<frozen importlib._bootstrap_external>", line 790, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/home/geonatureadmin/geonature/backend/geonature/migrations/env.py", line 88, in <module>
        run_migrations_online()
      File "/home/geonatureadmin/geonature/backend/geonature/migrations/env.py", line 82, in run_migrations_online
        context.run_migrations()
      File "<string>", line 8, in run_migrations
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/runtime/environment.py", line 937, in run_migrations
        self.get_context().run_migrations(**kw)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
        step.migration_fn(**kw)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/ref_geo/migrations/versions/795f6ea8ec45_cor_linear_area.py", line 25, in upgrade
        op.get_bind().execute(stmt)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
        return meth(self, multiparams, params)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
        ret = self._execute_context(
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
        self._handle_dbapi_exception(
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
        util.raise_(
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
        raise exception
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
        self.dialect.do_execute(
      File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) ERREUR:  la relation « ref_geo.l_linears » n'existe pas

    [SQL: -- cor_areas
    -- - table de correspondance entre un groupe de zonage et ses éléments
    --     par exemple une régions et ses départements ou ses communes.

    CREATE TABLE ref_geo.cor_areas (
        id_area_group integer,
        id_area integer
    );

    COMMENT ON TABLE ref_geo.cor_areas IS 'Table de correspondance des intersections des zonages. Non remplie par défaut.';

    ALTER TABLE ref_geo.cor_areas
        ADD CONSTRAINT fk_ref_geo_cor_areas_id_area_group FOREIGN KEY (id_area_group)
        REFERENCES ref_geo.l_areas(id_area)
        ON UPDATE CASCADE ON DELETE CASCADE;

    ALTER TABLE ref_geo.cor_areas
        ADD CONSTRAINT fk_ref_geo_cor_areas_id_area FOREIGN KEY (id_area)
        REFERENCES ref_geo.l_areas(id_area)
        ON UPDATE CASCADE ON DELETE CASCADE;

    CREATE INDEX ref_geo_cor_areas_id_area ON ref_geo.cor_areas USING btree(id_area);
    CREATE INDEX ref_geo_cor_areas_id_area_group ON ref_geo.cor_areas USING btree(id_area_group);

    -- cor_linear_area
    -- - Table de correspondance entre les éléments lineaires et les éléments de zonage
    --     par exemple pour trouver rapidement les routes d'une communes
    --     ou inversement les communes traversée par un linéaire

    CREATE TABLE ref_geo.cor_linear_area (
        id_linear integer,
        id_area integer
    );

    COMMENT ON TABLE ref_geo.cor_areas IS 'Table de correspondance entre les éléments lineaires et les éléments de zonage. Non remplie par défaut';

    ALTER TABLE ref_geo.cor_linear_area
        ADD CONSTRAINT fk_ref_geo_cor_linear_id_area_group FOREIGN KEY (id_area)
        REFERENCES ref_geo.l_areas(id_area)
        ON UPDATE CASCADE ON DELETE CASCADE;

    ALTER TABLE ref_geo.cor_linear_area
        ADD CONSTRAINT fk_ref_geo_cor_linear_id_lineair_group FOREIGN KEY (id_linear)
        REFERENCES ref_geo.l_linears(id_linear)
        ON UPDATE CASCADE ON DELETE CASCADE;

    CREATE INDEX ref_geo_cor_linear_area_id_area ON ref_geo.cor_linear_area USING btree(id_area);
    CREATE INDEX ref_geo_cor_linear_area_id_linear ON ref_geo.cor_linear_area USING btree(id_linear);
    ]
    (Background on this error at: http://sqlalche.me/e/13/f405)

En vérifiant, je n'avais effectivement pas la table l_linears d'installé en 2.12.3...

**Contournement**
Installation manuelle de la table

    CREATE TABLE ref_geo.l_linears (
      id_linear serial4 NOT NULL,
      id_type int4 NOT NULL,
      linear_name varchar(250) NOT NULL,
      linear_code varchar(25) NOT NULL,
      "enable" bool NOT NULL DEFAULT true,
      geom public.geometry(geometry, 2154) NULL,
      geojson_4326 varchar NULL,
      "source" varchar(250) NULL,
      additional_data jsonb NULL,
      meta_create_date timestamp NULL,
      meta_update_date timestamp NULL,
      CONSTRAINT l_linears_id_type_linear_code_key UNIQUE (id_type, linear_code),
      CONSTRAINT pk_ref_geo_l_linears_id_linear PRIMARY KEY (id_linear),
      CONSTRAINT fk_ref_geo_l_linears_id_type FOREIGN KEY (id_type) REFERENCES ref_geo.bib_linears_types(id_type) ON UPDATE CASCADE
    );
    CREATE INDEX ref_geo_l_linears_geom_idx ON ref_geo.l_linears USING gist (geom);

A voir pourquoi la table n'a pas été installé à l'origine lors d'une précédente migration :)
Je poste quand même un ticket pour avoir la trace

**Comment by joelclems** [comment]
normalement cette table est installée dans la migration f7374cd6e38d (qui est sensée être passée d'après les logs)

**Comment by joelclems** [comment]
d'après ton patch tu avait déjà la table `ref_geo.bib_linears_types` qui arrive avec la même migration que celle `l_linears`

**Comment by maximetoma** [comment]
Effectivement j'avais bien cette table, il y a pu y avoir une suppression de la table de ma part même si je ne vois pas pourquoi...
J'évite de toucher aux tables natives de GeoNature et encore plus de les supprimer ^^' Peut être une fausse manip ? :/

**Comment by jacquesfize** [comment]
Des nouvelles sur la suppression de `l_linears` ?
