### ISSUE TITLE
[VALIDATION] Internal servor error pour l'accès au module validation

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#3021]
**Version**
2.14.0

**Description du bug**
Un utilisateur, dépendant d'un groupe qui a les droits d'accès au module validation, a une internal server error lorsqu'il accède au module, et ne voit donc aucune donnée. Le groupe dont il dépend à les droits de validation pour les données de son organisme. 
Question : Le validateur est il obligé de pouvoir valider les données de l'ensemble des utilisateurs de l'instance GeoNature et non seulement de son organisme ? 

**Comportement attendu**
L'utilisateur accède au module de validation et peut valider les données de son organisme et ne voit pas les données des autres organismes.

**Comment reproduire**
Créer un groupe qui a les droits de validation des données de son organisme uniquement. 
Créer un utilisateur qui dépend de ce groupe. 
Accéder au module validation avec cet utilisateur. 

**Logs**

```
[2024-05-06 11:55:23 +0200] [1307572] [ERROR] Exception on /validation [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 62, in decorated_view
    return view_func(*args, **kwargs)
  File "/home/geonatureadmin/geonature/contrib/gn_module_validation/backend/gn_module_validation/blueprint.py", line 166, in get_synthese_data
    SyntheseQuery(
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 531, in filter_query_all_filters
    self.apply_all_filters(user, permissions)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 505, in apply_all_filters
    self.filter_query_with_cruved(user, scope=permissions)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 222, in filter_query_with_cruved
    datasets = DB.session.scalars(TDatasets.filter_by_scope(scope)).all()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1476, in all
    return self._allrows()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 412, in _allrows
    for made_row, sig_row in [
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 415, in <listcomp>
    strategy(made_row) if strategy else made_row,
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 193, in require_unique
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections
```

**Comment by camillemonchicourt** [comment]
Le V du CRUVED n'a aucun usage nul part.
Pour les permissions dans le module VALIDATION, on s'appuie sur le C du module Validation.

**Comment by RNF-SI** [comment]
Oui c'est bien sur ce paramètre que je joue, mais c'est la définition d'une restriction aux "données de mon organisme" qui ne fonctionne pas. Avec la permission suivante ça fonctionne mais l'utilisateur voit toutes les données de tout le monde : 
![image](https://github.com/PnX-SI/GeoNature/assets/43465924/9e2eab4f-55c2-4425-b4d7-88715ef79d27)

**Comment by jacquesfize** [comment]
Bonjour @RNF-SI ,

Un fix (#2958) est disponible dans la 2.14.1.

**Comment by RNF-SI** [comment]
Ah cool merci ! Ça m'apprendra à pas être up to date !
