### ISSUE TITLE
Sensibilité : erreur retournée par : geonature sensitivity info

### ISSUE THREAD

**Issue by blaisegeo** [PnX-SI/GeoNature#3208]
Je débute sur la gestion de la sensibilité. J'essaie de lancer quelques commandes dans un terminal comme indiqué dans la doc administrateur, mais je rencontre l'erreur suivante : 

**Version**
Version de GeoNature : 2.14

**Description du bug**
Dans un terminal, la commande : 
`$ geonature sensitivity refresh-rules-cache`
prend un certain temps à s'exécuter, mais ne retourne pas d'erreur.
Par contre, ensuite la commande : 
`$ geonature sensitivity info`
retourne l'erreur suivante : 

```
(venv) geonatureadmin@debvbgn:~/geonature$ geonature sensitivity info
Nombre de règle de sensibilité :
        Total : 24304
        Règles actives : 24304
        Règles actives extrapolées aux taxons enfants : 31906
Nombre de règles de sensibilité par source (actives / total):
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 858, in __getattr__
    return getattr(self.comparator, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Comparator' object has no attribute 'where'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/flask/cli.py", line 386, in decorator
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geonatureadmin/geonature/backend/geonature/core/sensitivity/routes.py", line 56, in info
    .where(SensitivityRule.active == True)
     ^^^^^
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 860, in __getattr__
    util.raise_(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
AttributeError: Neither 'count' object nor 'Comparator' object has an attribute 'where'
(venv) geonatureadmin@debvbgn:~/geonature$
```

**Comportement attendu**
Affichage des statistiques sur les règles présentes ?

**Comment reproduire**
Activer l'environnement virtuel, puis lancer la commande : 
`$ geonature sensitivity info`

**Logs**
Aucune trace dans les logs.

**Comment by jacquesfize** [comment]
@blaisegeo, merci pour le retour ! la #3216 devrait régler ce problème :)

**Comment by blaisegeo** [comment]
@jacquesfize : Testé avec ta modif dans geonature/backend/geonature/core/sensitivity/routes.py , ça ne retourne plus d'erreur et ça donne des infos sur : 
- Nombre de règle de sensibilité
- Nombre de règles de sensibilité par source
- Nombre de taxons
Don j'ai l'impression que ça fonctionne comme il faut.
Merci !
