### ISSUE TITLE
Plantage a l'installation :  Can't resolve './routing/app-routing.module'

### ISSUE THREAD

**Issue by LousyJohnny** [PnX-SI/GeoNature#437]
Bonjour,

J'essaye d'installer en local sur mon Ubuntu 18.04.
Le script install_app.sh plante sur un fichier non trouvé. Effectivement, on ne le trouve pas dans l'arborescence git ( on trouve un app-routing.module.ts **.sample** )

D'où pourrait venir le problème ?
Pour info j'avais deja un environnement npm / angular etc... , 
J'avais lancé le script d'install principal, mais au final l'appli ne marchait, en investiguant j'ai vu que le répertoire 'dist' n'existait pas, c'est pour cela que je lance maintenant directement le install_app.sh

Ci-dessous la stack correspondante :
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './routing/app-routing.module' in '/home/molivera/geonature/frontend/src/app'
resolve './routing/app-routing.module' in '/home/molivera/geonature/frontend/src/app'
  using description file: /home/molivera/geonature/frontend/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/molivera/geonature/frontend/package.json (relative path: ./src/app)
    using description file: /home/molivera/geonature/frontend/package.json (relative path: ./src/app/routing/app-routing.module)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/molivera/geonature/frontend/src/app/routing/app-routing.module doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/molivera/geonature/frontend/src/app/routing/app-routing.module.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/molivera/geonature/frontend/src/app/routing/app-routing.module.js doesn't exist
      as directory
        /home/molivera/geonature/frontend/src/app/routing/app-routing.module doesn't exist
[/home/molivera/geonature/frontend/src/app/routing/app-routing.module]
[/home/molivera/geonature/frontend/src/app/routing/app-routing.module.ts]
[/home/molivera/geonature/frontend/src/app/routing/app-routing.module.js]
[/home/molivera/geonature/frontend/src/app/routing/app-routing.module]
 @ ./src/app/app.module.ts 25:0-55
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in /home/molivera/geonature/frontend/src/app/app.module.ts (23,25): Cannot find module './routing/app-routing.module'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ./routing/app-routing.module relative to /home/molivera/geonature/frontend/src/app/app.module.ts., resolving symbol AppModule in /home/molivera/geonature/frontend/src/app/app.module.ts, resolving symbol AppModule in /home/molivera/geonature/frontend/src/app/app.module.ts
    at syntaxError (/home/molivera/geonature/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/molivera/geonature/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/home/molivera/geonature/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/home/molivera/geonature/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/home/molivera/geonature/frontend/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/molivera/geonature/frontend/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/molivera/geonature/frontend/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/molivera/geonature/frontend/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/molivera/geonature/frontend/node_modules/@ngtools/webpack/src/plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/molivera/geonature/frontend/node_modules/@ngtools/webpack/src/plugin.js:495:24)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geonature@0.0.0 build: `ng build --prod --aot=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geonature@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/molivera/.npm/_logs/2018-09-25T07_04_53_173Z-debug.log
```
Le contenu du fichier de log : 
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/home/molivera/.npm-global/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle geonature@0.0.0~prebuild: geonature@0.0.0
6 info lifecycle geonature@0.0.0~build: geonature@0.0.0
7 verbose lifecycle geonature@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle geonature@0.0.0~build: PATH: /home/molivera/.npm-global/lib/node_modules/npm/bin/node-gyp-bin:/home/molivera/geonature/frontend/node_modules/.bin:/home/molivera/geonature/backend/venv/bin:/opt/xtensa-esp32-elf/bin:/home/molivera/.npm-global/bin:/home/molivera/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/xtensa-esp32-elf/:/snap/bin:/home/molivera/bin:/usr/local/java/jdk1.8.0_102/bin
9 verbose lifecycle geonature@0.0.0~build: CWD: /home/molivera/geonature/frontend
10 silly lifecycle geonature@0.0.0~build: Args: [ '-c', 'ng build --prod --aot=false' ]
11 silly lifecycle geonature@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle geonature@0.0.0~build: Failed to exec build script
13 verbose stack Error: geonature@0.0.0 build: `ng build --prod --aot=false`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/molivera/.npm-global/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/molivera/.npm-global/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid geonature@0.0.0
15 verbose cwd /home/molivera/geonature/frontend
16 verbose Linux 4.15.0-34-generic
17 verbose argv "/usr/bin/node" "/home/molivera/.npm-global/bin/npm" "run" "build"
18 verbose node v8.11.4
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error geonature@0.0.0 build: `ng build --prod --aot=false`
22 error Exit status 1
23 error Failed at the geonature@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by TheoLechemia** [comment]
Bonjour,

Le problème vient un peu en amont. C'est la commande `geonature generate_frontend_modules_route` qui lance la génération de ce fichier. La commande n'a pas du être créé, et c'est surement lié à un paquet python qui n'a pas été bien installé.
Est ce que tu peux vérifier depuis le virtual env ( `source venv/bin/activate`) si il y a un retour lorsque tu tapes ``geonature``.

Autre question: est-ce que la base à été bien installé ?e (voir le fichier de log `var/log/install_db.log` et regarder s'il y a des erreurs  ) ? 
Si c'est OK de ce côté là, je relancerais le script ``install_app.sh`` en regardant attentivement les erreurs qui peuvent remonter.

**Comment by camillemonchicourt** [comment]
Je viens d'avoir la même erreur mais dans le cas d'une mise à jour de la Beta5 vers la future RC3. 
Mais en lançant le script ``migrate.sh`` et j'ai exécuté celui-ci avant de faire les mises à jour de la BDD, ce qui était une très mauvaise idée. 

Par contre j'ai vérifié et j'ai bien les commandes ``geonature`` de fonctionnelles. 

@LousyJohnny tu as eu cette erreur sur une nouvelle installation de GeoNature (quelle version?) ou sur une mise à jour ?

**Comment by LousyJohnny** [comment]
Bonjour,

Désolé pour le délai dans la réponse.
C'est une toute nouvelle installation.

Concernant les commandes demandées :
```
source venv/bin/activate
bash: venv/bin/activate: No such file or directory
```

La base n'a pas été installée
```
cat var/log/install_db.log
cat: var/log/install_db.log: No such file or directory
```


Je vais reprende l'installation depuis le début et je vous tiens au courant.

**Comment by camillemonchicourt** [comment]
OK merci.

**Comment by gildeluermoz** [comment]
pour activer le venv il faut d'abord être dans le répertoire backend

```
cd backend
source venv/bin/activate
```

**Comment by camillemonchicourt** [comment]
Un autre utilisateur a eu un problème similaire sur un Debian 9 installé en local.
C'était PostgreSQL qui ne s'est pas installé lors du déroulement du script ``install_all.sh`` et il a donc corrigé son problème en installant PostgreSQL manuelle avant.
