### ISSUE TITLE
Personnaliser son instance : questions bêtes

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#453]
_(pardonnez par avance mon inexpérience en configuration d'application)_

En cours de tests sur mon instance GeoNature V2, je tente de la personnaliser un peu (logos, textes) avant de la mettre entre les mains des collègues pour une phase de tests.

Est-on obligé, après chaque modification de contenu HTML, de lancer le `update_configuration` ?
```
source venv/bin/activate
geonature update_configuration
deactivate
```
Ou y a-t-il une méthode plus rapide ? (*)

Par ailleurs, j'avais modifié le logo `logo_structure.png` situé dans `/home/geonatureadmin/geonature/frontend/dist/custom/images`, mais à chaque `update_configuration`, il est remis d'origine.
Quelle serait la méthode pour que le logo de ma structure ne soit pas écrasé à chaque `update_configuration` ?

(*) J'ai durant l'execution du `update_configuration` ce message d'erreur, qui ne semble pas bloquant, mais que je vous signale au cas où : 
```
@angular/compiler-cli@4.4.7 requires typescript@'>=2.1.0 <2.4.0' but 2.9.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.
Please run the following command to install a compatible version of TypeScript.
    npm install typescript@'>=2.1.0 <2.4.0'
To disable this warning run "ng set warnings.typescriptMismatch=false".
```

**Comment by sig-pnrnm** [comment]
Je me rends compte que j'ai en fait pas mal de messages d'erreurs (d'attention, plutôt) lors du `update_configuration`.

Je vous les mets ici, au cas où : 

```
WARNING in ../contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
194:103-132 "export 'DynamicFormGeneratorComponent' was not found in '@geonature_common/form/dynamic-form-generator/dynamic-form-generator.component'
    at HarmonyImportSpecifierDependency._getErrors (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/geonatureadmin/geonature/frontend/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ../contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
 @ ../contrib/occtax/frontend/app/gnModule.module.ts
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ../contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
194:54-83 "export 'DynamicFormGeneratorComponent' was not found in '@geonature_common/form/dynamic-form-generator/dynamic-form-generator.component'
    at HarmonyImportSpecifierDependency._getErrors (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/geonatureadmin/geonature/frontend/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ../contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
 @ ../contrib/occtax/frontend/app/gnModule.module.ts
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./src/app/GN2CommonModule/form/date/date.component.ts
70:54-67 "export 'NgbDateStruct' was not found in '@ng-bootstrap/ng-bootstrap'
    at HarmonyImportSpecifierDependency._getErrors (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/geonatureadmin/geonature/frontend/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./src/app/GN2CommonModule/form/date/date.component.ts
 @ ./src/app/GN2CommonModule/GN2Common.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./src/app/GN2CommonModule/form/date/date.component.ts
70:87-100 "export 'NgbDateStruct' was not found in '@ng-bootstrap/ng-bootstrap'
    at HarmonyImportSpecifierDependency._getErrors (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/geonatureadmin/geonature/frontend/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/geonatureadmin/geonature/frontend/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./src/app/GN2CommonModule/form/date/date.component.ts
 @ ./src/app/GN2CommonModule/GN2Common.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
...ok
```

**Comment by DonovanMaillard** [comment]
Bonjour Sylvain, 

Pour une fois que je sais répondre, j'en profite ;)
 La commande à lancer n'est pas update_configuration, mais npm run build en te placant dans le répertoire geonature/frontend. 

C'est dans une PR de la doc, mais Camille a refait des modifs récemment et c'est pas encore validé.
Si tu arrives à voir la PR, j'y ai mis un volet sur la "customisation"

**Comment by camillemonchicourt** [comment]
La PR en question : https://github.com/PnX-SI/GeoNature/blob/156b544bcc7d0c97c3f6933305557d1ee104a454/docs/admin-manual.rst

**Comment by sig-pnrnm** [comment]
> Si tu arrives à voir la PR, j'y ai mis un volet sur la "customisation"

Très bonne initiative !
J'étais justement en train de me faire mon vade-mecum pour la personnalisation de notre instance
(ça me permet de découvrir le Markdown et Github : https://github.com/sig-pnrnm/GeoNature-Tests/blob/master/geonaturev2/adaptations_pnrnm.md )

`npm run build` est un peu plus rapide, mais j'ai encore les mêmes messages d'attention (c'est grave, docteurs ?)...
Et ça met quand même 1m12s pour s'éxecuter : j'ai comme dans l'idée que c'est un peu long pour juste quelques modifs HTML ? N'y aurait-il pas une commande plus sommaire pour juste les modifs cosmétiques de personnalisation ?
(mais ça marche, donc rien de prioritaire !)

**Comment by camillemonchicourt** [comment]
Les warning on le sait, c'est pas grave.
En mode DEV il n'y a pas à rebuild le frontend pour voir chaque modification.
En mode PROD il n'y a pas plus rapide.

**Comment by sig-pnrnm** [comment]
> En mode DEV il n'y a pas à rebuild le frontend pour voir chaque modification.
> En mode PROD il n'y a pas plus rapide.

Intéressant, je commence donc à comprendre l'intérêt de ces 2 modes :wink:

**Comment by camillemonchicourt** [comment]
Une méthode est maintenant documentée pour pouvoir customiser GeoNature et ne pas avoir à relancer le build du frontend à chaque modification : https://github.com/PnX-SI/GeoNature/commit/caf489ddeb57833f57ded1fb454d8ccdb8138853#diff-8ecc5c84761524b50f3c94f5bb399d2a
