### ISSUE TITLE
Update configuration : problème du vendredi soir

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#468]
Désolé pour ce bug qui ne m'arrive que maintenant, après plusieurs executions des commandes sans incidents cette semaine...

J'ai juste modifié le fichier `map.config.ts` pour affiner le niveau de zoom et le centre de la carte par défaut.

J'ai ensuite executé un `geonature update_configuration` (j'aurais certainement pu faire un simple `npm run build`), et j'ai des gros messages d'erreurs pas gentils du tout :cry: : 

Voici le log : 
```

0 info it worked if it ends with ok
1 verbose cli [ '/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin/node',
1 verbose cli   '/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle geonature@0.0.0~prebuild: geonature@0.0.0
6 silly lifecycle geonature@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle geonature@0.0.0~build: geonature@0.0.0
8 verbose lifecycle geonature@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle geonature@0.0.0~build: PATH: /home/geonatureadmin/.nvm/versions/node/v8.1.1/lib/node_modules/npm/bin/node-gyp-bin:/home/geonatureadmin/geonature/frontend/node_modules/.bin:/home/geonatureadmin/geonature/backend/venv/bin:/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle geonature@0.0.0~build: CWD: /home/geonatureadmin/geonature/frontend
11 silly lifecycle geonature@0.0.0~build: Args: [ '-c', 'ng build --prod --aot=false' ]
12 silly lifecycle geonature@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle geonature@0.0.0~build: Failed to exec build script
14 verbose stack Error: geonature@0.0.0 build: `ng build --prod --aot=false`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/geonatureadmin/.nvm/versions/node/v8.1.1/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/geonatureadmin/.nvm/versions/node/v8.1.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid geonature@0.0.0
16 verbose cwd /home/geonatureadmin/geonature/frontend
17 verbose Linux 4.9.0-8-amd64
18 verbose argv "/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin/node" "/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin/npm" "run" "build"
19 verbose node v8.1.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error geonature@0.0.0 build: `ng build --prod --aot=false`
23 error Exit status 1
24 error Failed at the geonature@0.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

Et si je fais un `npm run build`, voici le log : 
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin/node',
1 verbose cli   '/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose stack Error: ENOENT: no such file or directory, open '/home/geonatureadmin/geonature/backend/package.json'
5 verbose cwd /home/geonatureadmin/geonature/backend
6 verbose Linux 4.9.0-8-amd64
7 verbose argv "/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin/node" "/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin/npm" "run" "build"
8 verbose node v8.1.1
9 verbose npm  v5.0.3
10 error path /home/geonatureadmin/geonature/backend/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/home/geonatureadmin/geonature/backend/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]
```

Pourquoi tant de haine un vendredi soir ???

**Comment by sig-pnrnm** [comment]
> no such file or directory, open '/home/geonatureadmin/geonature/backend/package.json'

Effectivement, je n'ai pas ce fichier `package.json` dans le dossier backend.
Pourtant, je n'ai pas (ou en tout cas, pas volontairement... et je n'ai rien bu d'alcoolisé ce midi...) supprimé ce fichier !?

**Comment by DonovanMaillard** [comment]
Pour info, 

J'ai eu la même erreur hier sur mon petit serveur test, les forums m'ont laissé comprendre que c'etait peut etre un soucis de performance qui renvoyait cette erreur (mais ai-je bien compris... du langage geek en anglais ca fait beaucoup d'un coup ;) )

J'ai refait la même manip sur un serveur plus performant et pas de soucis, c'est passé.

**Comment by gildeluermoz** [comment]
package.json est dans frontend. Tu as du lancer npm run build depuis le backend.
C'est l'effet vendredi soir....

**Comment by gildeluermoz** [comment]
Est-ce que tu avais bien lancé la première commande (geonature update_configuration) depuis l'environnement virtuel ?
cd backend
source venv/bin/activate

**Comment by sig-pnrnm** [comment]
> Est-ce que tu avais bien lancé la première commande (geonature update_configuration) depuis l'environnement virtuel ?

Pour ce qui est de vendredi, j'ai un doute maintenant.
Mais je viens de le refaire, et là, je suis bien dans l'environnement virtuel, dans backend : 

```shell
geonatureadmin@geonature2:~$ cd geonature
geonatureadmin@geonature2:~/geonature$ cd backend
geonatureadmin@geonature2:~/geonature/backend$ source venv/bin/activate
(venv) geonatureadmin@geonature2:~/geonature/backend$ geonature update_configura                                                                                      tion
Update app configuration
[sudo] Mot de passe de geonatureadmin : 
Restarted supervisord
Generating configuration
...ok



> geonature@0.0.0 build /home/geonatureadmin/geonature/frontend
> ng build --prod --aot=false


@angular/compiler-cli@4.4.7 requires typescript@'>=2.1.0 <2.4.0' but 2.9.2 was f                                                                                      ound instead.
Using this version can result in undefined behaviour and difficult to debug prob                                                                                      lems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

EACCES: permission denied, unlink '/home/geonatureadmin/geonature/frontend/dist/                                                                                      0.b7c36c0e930c177436fc.chunk.js'
Error: EACCES: permission denied, unlink '/home/geonatureadmin/geonature/fronten                                                                                      d/dist/0.b7c36c0e930c177436fc.chunk.js'
    at Object.fs.unlinkSync (fs.js:1066:18)
    at rimrafSync (/home/geonatureadmin/geonature/frontend/node_modules/fs-extra                                                                                      /lib/remove/rimraf.js:254:15)
    at options.readdirSync.forEach.f (/home/geonatureadmin/geonature/frontend/no                                                                                      de_modules/fs-extra/lib/remove/rimraf.js:291:39)
    at Array.forEach (native)
    at rmkidsSync (/home/geonatureadmin/geonature/frontend/node_modules/fs-extra                                                                                      /lib/remove/rimraf.js:291:26)
    at rmdirSync (/home/geonatureadmin/geonature/frontend/node_modules/fs-extra/                                                                                      lib/remove/rimraf.js:281:7)
    at Object.rimrafSync [as removeSync] (/home/geonatureadmin/geonature/fronten                                                                                      d/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at Class.run (/home/geonatureadmin/geonature/frontend/node_modules/@angular/                                                                                      cli/tasks/build.js:29:16)
    at Class.run (/home/geonatureadmin/geonature/frontend/node_modules/@angular/                                                                                      cli/commands/build.js:246:40)
    at resolve (/home/geonatureadmin/geonature/frontend/node_modules/@angular/cl                                                                                      i/ember-cli/lib/models/command.js:261:20)
    at Promise (<anonymous>)
    at Class.validateAndRun (/home/geonatureadmin/geonature/frontend/node_module                                                                                      s/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/home/geonatureadmin/geonature/frontend/node_m                                                                                      odules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geonature@0.0.0 build: `ng build --prod --aot=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geonature@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                      ging output above.


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.0.3 → 6.4.1    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/geonatureadmin/.npm/_logs/2018-10-15T08_00_49_461Z-debug.log
...ok


(venv) geonatureadmin@geonature2:~/geonature/backend$
```

Mais je vois des messages d'erreur liés au frontend ... ???

**Comment by camillemonchicourt** [comment]
Je viens de lancer un ``geonature update_configuration`` qui s'est bien déroulé donc là je ne vois pas d'où vient ton problème : 

```
test@testdebian9:~$ cd geonature/backend/
test@testdebian9:~/geonature/backend$ source venv/bin/activate
(venv) test@testdebian9:~/geonature/backend$ geonature update_configuration
Update app configuration
[sudo] Mot de passe de test : 
Restarted supervisord
Generating configuration
...ok



> geonature@0.0.0 build /home/test/geonature/frontend
> ng build --prod --aot=false


@angular/compiler-cli@4.4.7 requires typescript@'>=2.1.0 <2.4.0' but 2.9.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

 17% building modules 63/96 modules 33 active ...angular/material/esm5/material.esDate: 2018-10-15T08:52:09.973Z                                                        Hash: 5f8804568146fb67b5b2
Time: 102375ms
chunk {0} 0.b7c36c0e930c177436fc.chunk.js () 227 kB  [rendered]
chunk {1} 1.4d0ab39ee7a85dbf66a6.chunk.js () 97.2 kB  [rendered]
chunk {2} 2.a56562518bd590cd12e3.chunk.js () 29 kB  [rendered]
chunk {3} 3.208a6f018fca2070b876.chunk.js () 41.6 kB  [rendered]
chunk {4} 4.c59f954261b69ce605de.chunk.js () 4.15 kB  [rendered]
chunk {5} polyfills.9b094accf4bf62db599e.bundle.js (polyfills) 64.8 kB [initial] [rendered]
chunk {6} main.e653db6f5175d238340e.bundle.js (main) 131 kB [initial] [rendered]
chunk {7} styles.2da4847de98cb42426be.bundle.css (styles) 391 kB [initial] [rendered]
chunk {8} vendor.3f97b731be8cefefefd1.bundle.js (vendor) 3.18 MB [initial] [rendered]
chunk {9} inline.f2ec7829c3e00debcc4d.bundle.js (inline) 1.57 kB [entry] [rendered]

WARNING in ../contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
194:103-132 "export 'DynamicFormGeneratorComponent' was not found in '@geonature_common/form/dynamic-form-generator/dynamic-form-generator.component'
    at HarmonyImportSpecifierDependency._getErrors (/home/test/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/test/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/test/geonature/frontend/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/test/geonature/frontend/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ../contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
 @ ../contrib/occtax/frontend/app/gnModule.module.ts
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ../contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
194:54-83 "export 'DynamicFormGeneratorComponent' was not found in '@geonature_common/form/dynamic-form-generator/dynamic-form-generator.component'
    at HarmonyImportSpecifierDependency._getErrors (/home/test/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/test/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/test/geonature/frontend/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/test/geonature/frontend/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ../contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.ts
 @ ../contrib/occtax/frontend/app/gnModule.module.ts
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./src/app/GN2CommonModule/form/date/date.component.ts
70:54-67 "export 'NgbDateStruct' was not found in '@ng-bootstrap/ng-bootstrap'
    at HarmonyImportSpecifierDependency._getErrors (/home/test/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/test/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/test/geonature/frontend/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/test/geonature/frontend/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./src/app/GN2CommonModule/form/date/date.component.ts
 @ ./src/app/GN2CommonModule/GN2Common.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./src/app/GN2CommonModule/form/date/date.component.ts
70:87-100 "export 'NgbDateStruct' was not found in '@ng-bootstrap/ng-bootstrap'
    at HarmonyImportSpecifierDependency._getErrors (/home/test/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/test/geonature/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/test/geonature/frontend/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/test/geonature/frontend/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/test/geonature/frontend/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./src/app/GN2CommonModule/form/date/date.component.ts
 @ ./src/app/GN2CommonModule/GN2Common.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
...ok
```

**Comment by gildeluermoz** [comment]
Sylvain,
regarde ton message d'erreur, tu as des "permissions denied".
Check les droits sur tes répertoires. Il y a peut-être un soucis qq part.

**Comment by sig-pnrnm** [comment]
> regarde ton message d'erreur, tu as des "permissions denied".
> Check les droits sur tes répertoires. Il y a peut-être un soucis qq part.

En effet, quand je lance les commandes en root, je n'ai pas de message d'erreur... ???
Pourtant, je ne pense pas avoir modifié les droits sur les dossiers / fichiers !?

**Comment by camillemonchicourt** [comment]
Tu as peut être lancé la commande en root précédemment du coup il en a pris les droits et du coup geonatureadmin n'en a plus les droits.

**Comment by sig-pnrnm** [comment]
> Tu as peut être lancé la commande en root précédemment du coup il en a pris les droits et du coup geonatureadmin n'en a plus les droits.

Aïe, c'est possible ça... :stuck_out_tongue: 
C'est grave docteur ?

Y'aurait-il une autre méthode que de "`tout péter`" pour redonner les droits à geonatureadmin ?

**Comment by camillemonchicourt** [comment]
Oui en effet, c'est pas une bonne chose. 
Déjà regarde qui est propriétaire et quels sont les droits sur tes répertoires du Frontend : 

![frontend-owner](https://user-images.githubusercontent.com/4418840/47004405-c98f1400-d131-11e8-8d6f-b61a4dfa78f2.jpg)

Si c'est root qui est propriétaire des répertoires, cela confirmera...

Ensuite avec root (ou plutôt en sudo) et la commande chown, tu peux repasser ton utilisateur geonatureadmin en propriétaire : http://debian-facile.org/doc:systeme:chown

Mais si tu as fait des choses en root, il y a peut-être d'autres effets de bord qui apparaîtront plus tard...

La doc indique bien : 

> Se reconnecter en SSH au serveur avec le nouvel utilisateur pour ne pas faire l’installation en root.
> 
> On ne se connectera plus en root. Si besoin d’exécuter des commandes avec des droits d’administrateur, on les précède de sudo.
> 
> Il est d’ailleurs possible de renforcer la sécurité du serveur en bloquant la connexion SSH au serveur avec root.

Au début quand on a le serveur on n'a que root donc on fait les premières étapes avec cet utilisateur (notamment la création d'un utilisateur) mais ensuite on ne fait plus jamais rien en root pour éviter ce genre de problèmes. C'est une pratique de base. Idéalement même on désactive la possibilité de se connecter en root comme ça on est sur de pas le faire... :-)

Bon si c'est ça, ça me rassure car ce n'était pas un "bug" mais un "problème".

**Comment by sig-pnrnm** [comment]
> Bon si c'est ça, ça me rassure car ce n'était pas un "bug" mais un "problème".

Et que le "problème" se situe, à nouveau, entre ma chaise et mon clavier !!!! :stuck_out_tongue_closed_eyes: 

![frontend](https://user-images.githubusercontent.com/26482054/47006095-715a1100-d135-11e8-9ec2-252ac607a399.png)

> on ne fait plus jamais rien en root

Je le copierai 100x !!!
(mais c'est en faisant ce genre d'erreur qu'on apprend ! :smiley:  )

**Comment by camillemonchicourt** [comment]
C'est clair, je l'ai fait aussi. 
Évitons peut-être le terme "bug" dans les titres des tickets. 

Un truc comme ça devrait faire ton affaire : 

```
cd /home/geonatureadmin/geonature/frontend
sudo chown -R geonatureadmin dist
```

**Comment by gildeluermoz** [comment]
Ok. Je ferme le ticket. Un soucis de plus en moins à corriger !

**Comment by sig-pnrnm** [comment]
> Un truc comme ça devrait faire ton affaire

Pour info, c'est tout bon !
Plus de messages d'erreur, ni avec `geonature update_configuration` depuis l'environnement virtuel, ni avec `npm run build` depuis le frontend.
:+1:

**Comment by gildeluermoz** [comment]
cool, merci Sylvain pour le retour

**Comment by TheoLechemia** [comment]
Juste pour clairifier:
- Quand on modifie de la customisation, il faut executer la commande ``npm run build`` depuis le répertoire frontend. C'est également possible de le faire grâce à la commande ``geonature frontend_build``. Je vais dire dans la doc de toujours utiliser cette commande, ça évitera les confusion et la multiplications de manière de faire.
- Quand on modifie de la conf: ``geonature update_configuration`` fait le boulot (derrière cette commande relance un ``npm run build``).

**Comment by camillemonchicourt** [comment]
Concernant les Warning lors du Build du frontend ils ont été corrigés : https://github.com/PnX-SI/GeoNature/commit/2a4afcf7734dfd1831fbe030f0b0d1364547720d
