### ISSUE TITLE
Installation Geonature sur CentOS 7

### ISSUE THREAD

**Issue by patricklbs** [PnX-SI/GeoNature#618]
Bonjour,
J'essaye d'installer Geonature sur une CentOS 7 j'ai une erreur le script install_app.sh ne va pas jusqu'au bout. Je vais d'abord vous donner les actions réalisées ci-dessous et les logs erreur ci-jointes. 

Merci de votre aide

Patrick.

[2019-04-12T10_51_15_152Z-debug.log](https://github.com/PnX-SI/GeoNature/files/3072999/2019-04-12T10_51_15_152Z-debug.log)

[Log_Geonature_Install_app.log](https://github.com/PnX-SI/GeoNature/files/3073001/Log_Geonature_Install_app.log)

```
useradd geonature
yum install httpd -y //pour avoir le user apache
usermod -g apache geonature
usermod -a -G root geonature



visudo
vgniqr  ALL=(ALL)       ALL


 
sudo yum install postgresql postgresql-server postgis postgresql-devel -y
sudo yum install python36 python36-devel python36-setuptools python36-pip python36-virtualenv gdal-python gdal-devel -y
sudo /usr/local/bin/pip install --upgrade pip virtualenv virtualenvwrapper

sudo yum groupinstall development -y //build-essential

sudo yum install npm supervisor -y




sudo postgresql-setup initdb
sudo systemctl enable postgresql
sudo systemctl start postgresql

cd

wget https://github.com/PnX-SI/GeoNature/archive/2.0.1.zip

unzip 2.0.1.zip
mv GeoNature-2.0.1/ geonature

cd geonature/config

cp settings.ini.sample settings.ini


vi settings.ini

drop_apps_db=true
my_url=http://geonature.mrs/
# GeoNature database name
db_name=geodb

# GeoNature database owner username
user_pg=geonature

# GeoNature database owner password
user_pg_pass=geonature234

python_path=/bin/python3.6





cd ../install
$ ./install_db.sh
[sudo] Mot de passe de geonature :


./install_app.sh 

```

La log 
````
0 info it worked if it ends with ok
1 verbose cli [ '/home/geonature/.nvm/versions/node/v8.1.1/bin/node',
1 verbose cli   '/home/geonature/.nvm/versions/node/v8.1.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle geonature@0.0.0~prebuild: geonature@0.0.0
6 silly lifecycle geonature@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle geonature@0.0.0~build: geonature@0.0.0
8 verbose lifecycle geonature@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle geonature@0.0.0~build: PATH: /home/geonature/.nvm/versions/node/v8.1.1/lib/node_modules/npm/bin/node-gyp-bin:/home/geonature/geonature/frontend/node_modules/.bin:/home/geonature/geonature/backend/venv/bin:/home/geonature/.nvm/versions/node/v8.1.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tivoli/tsm/client/ba/bin:/home/geonature/.local/bin:/home/geonature/bin
10 verbose lifecycle geonature@0.0.0~build: CWD: /home/geonature/geonature/frontend
11 silly lifecycle geonature@0.0.0~build: Args: [ '-c', 'ng build --prod --aot=false' ]
12 silly lifecycle geonature@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle geonature@0.0.0~build: Failed to exec build script
14 verbose stack Error: geonature@0.0.0 build: `ng build --prod --aot=false`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/geonature/.nvm/versions/node/v8.1.1/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/geonature/.nvm/versions/node/v8.1.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid geonature@0.0.0
16 verbose cwd /home/geonature/geonature/frontend
17 verbose Linux 3.10.0-957.10.1.el7.x86_64
18 verbose argv "/home/geonature/.nvm/versions/node/v8.1.1/bin/node" "/home/geonature/.nvm/versions/node/v8.1.1/bin/npm" "run" "build"
19 verbose node v8.1.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error geonature@0.0.0 build: `ng build --prod --aot=false`
23 error Exit status 1
24 error Failed at the geonature@0.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

````

**Comment by TheoLechemia** [comment]
Bonjour,
L'installation de GeoNature n'est testée que sur debian 9 et Ubuntu 18.
Cependant, de ce que je vois, le problème est en amont des logs fournit. La commande "geonature" n'a pas bien été installée, c'est surement dû à une erreur d'installation des paquets python.
Vous pouvez relancer la commande `install_app.sh` en redirigeant les logs vers un fichier pour avoir la trace complète de ce qu'il se passe.

**Comment by patricklbs** [comment]
Bonjour et merci pour la réponse rapide. Oui j'ai vu que geonature n'avait été testé que sur debian, mais j'ai pour mission et je l'accepte de l'installer sur CentOS 7 et ça pourrait vous servir on sait jamais :)

Pour la log complète 


[Log_Geonature_Install_app.log](https://github.com/PnX-SI/GeoNature/files/3073097/Log_Geonature_Install_app.log)

**Comment by TheoLechemia** [comment]
ça marche ;)
Les logs ne sont pas complet, il manque toute la partie d'installation des dépendances python, et de la commande "geonature" justement

**Comment by camillemonchicourt** [comment]
Merci pour ces retours, et n'hésitez pas à nous tenir au courant, voir à enrichir le script d'installation avec les parties spécifiques à Centos.

**Comment by patricklbs** [comment]
Voici la log de l'installation 

[log_geonature_app.log](https://github.com/PnX-SI/GeoNature/files/3073322/log_geonature_app.log)

@camillemonchicourt avec plaisir.

**Comment by TheoLechemia** [comment]
Il y a seulement une erreur ligne 105-106. Des paquets ont tenté d'être installé en python 2.7, alors que le virutalenv est en python 3.6... étrange.
Le reste de l'installation semble bien se passer.

Que renvoie la commande `ps -aux |grep gunicorn ` ?
Que renvoie la commande "geonature" : (depuis le répertoire `geonature/backend`, lancez ces commandes:
```
source venv/bin/activate
geonature
```

L'installation que vous avez lancé est une installation "autonome", il n'y a pas de configuration apache  réalisé dans le script. Il faut donc le faire manuelement:

Créer un fichier de configuration:

`sudo nano /etc/apache2/sites-available
`
y ajouter les lignes suivantes (en remplaçant MON_USER par votre utilisateur linux

```
Alias /geonature /home/<MON_USER>/geonature/frontend/dist   
<Directory /home/<MON_USER>/geonature/frontend/dist>
    Require all granted
</Directory>

<Location /geonature/api>
    ProxyPass http://127.0.0.1:8000
    ProxyPassReverse  http://127.0.0.1:8000
</Location>
```

puis:
```
sudo a2ensite geonature
sudo apachectl restart
```

Il y a une doc sur la conf apache ici:
https://geonature.readthedocs.io/fr/latest/conf-apache.html?highlight=apache

**Comment by patricklbs** [comment]
Bonjour ,

J'ai un tout petit peu avancé l'erreur concernant python 2 venait du fait que supervisor n'était pas démarré et le chemin du fichier de conf n'est pas le bon pour centos. Modifié dans le script.

gunicorn n'est pas starté le pf aux |grep gunicorn ne renvoi rien.

geonature :

```
(venv) [geonatureadmin@geonature install]$ cd ../backend/
(venv) [geonatureadmin@geonature backend]$ source venv/bin/activate
(venv) [geonatureadmin@geonature backend]$ geonature
Usage: geonature [OPTIONS] COMMAND [ARGS]...

  Group all the subcommands

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  activate_gn_module              Active un module gn installé Exemples: -...
  deactivate_gn_module            Desactive un module gn activé Exemples: -...
  dev_back                        Lance l'api du backend avec flask Exemples
                                  -...
  dev_front                       Démarre le frontend en mode develop
  frontend_build                  Lance le build du frontend
  generate_frontend_config        Génération des fichiers de configurations...
  generate_frontend_modules_route
                                  Génere le fichier de routing du frontend
                                  à...
  generate_frontend_tsconfig      Génere tsconfig du frontend
  install_command                 Install an alias of geonature_cmd.py in
                                  the...
  install_gn_module               Installation d'un module gn
  start_gunicorn                  Lance l'api du backend avec gunicorn
  supervisor                      Lance les actions du supervisor
  update_configuration            Regénère la configuration de
                                  l'application...
  update_module_configuration     Génère la config frontend d'un module...
```
Le build s'arrête à 10 % : 
```10% building modules 8/22 modules 14 active .../bootstrap/dist/css/bootstrap.min.cssNode#moveTo was deprDate: 2019-04-14T09:14:00.147Z                                                       Hash: 0b55d501489e36eb14af
Time: 137302ms
chunk {0} polyfills.7639510a089ebc50ec3b.bundle.js (polyfills) 64.8 kB [initial] [rendered]
chunk {1} main.66493025b8c0cc2fad84.bundle.js (main) 144 kB [initial] [rendered]
chunk {2} styles.ecf54aa57d1a4db55215.bundle.css (styles) 393 kB [initial] [rendered]
chunk {3} vendor.d1e480f3b91ce443346d.bundle.js (vendor) 3.45 MB [initial] [rendered]
chunk {4} inline.432f05fd305d98e31ab2.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './routing/app-routing.module' in '/home/geonatureadmin/geonature/frontend/src/app'
resolve './routing/app-routing.module' in '/home/geonatureadmin/geonature/frontend/src/app'
  using description file: /home/geonatureadmin/geonature/frontend/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/geonatureadmin/geonature/frontend/package.json (relative path: ./src/app)
    using description file: /home/geonatureadmin/geonature/frontend/package.json (relative path: ./src/app/routing/app-routing.module)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/geonatureadmin/geonature/frontend/src/app/routing/app-routing.module doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/geonatureadmin/geonature/frontend/src/app/routing/app-routing.module.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/geonatureadmin/geonature/frontend/src/app/routing/app-routing.module.js doesn't exist
      as directory
        /home/geonatureadmin/geonature/frontend/src/app/routing/app-routing.module doesn't exist
[/home/geonatureadmin/geonature/frontend/src/app/routing/app-routing.module]
[/home/geonatureadmin/geonature/frontend/src/app/routing/app-routing.module.ts]
[/home/geonatureadmin/geonature/frontend/src/app/routing/app-routing.module.js]
[/home/geonatureadmin/geonature/frontend/src/app/routing/app-routing.module]
 @ ./src/app/app.module.ts 25:0-55
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in /home/geonatureadmin/geonature/frontend/src/app/app.module.ts (23,25): Cannot find module './routing/app-routing.module'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ./routing/app-routing.module relative to /home/geonatureadmin/geonature/frontend/src/app/app.module.ts., resolving symbol AppModule in /home/geonatureadmin/geonature/frontend/src/app/app.module.ts, resolving symbol AppModule in /home/geonatureadmin/geonature/frontend/src/app/app.module.ts
    at syntaxError (/home/geonatureadmin/geonature/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/geonatureadmin/geonature/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/home/geonatureadmin/geonature/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/home/geonatureadmin/geonature/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/home/geonatureadmin/geonature/frontend/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/geonatureadmin/geonature/frontend/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/geonatureadmin/geonature/frontend/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/geonatureadmin/geonature/frontend/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/geonatureadmin/geonature/frontend/node_modules/@ngtools/webpack/src/plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/geonatureadmin/geonature/frontend/node_modules/@ngtools/webpack/src/plugin.js:495:24)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geonature@0.0.0 build: `ng build --prod --aot=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geonature@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/geonatureadmin/.npm/_logs/2019-04-14T09_14_00_254Z-debug.log
+ echo 'Désactiver le virtual env'
Désactiver le virtual env
+ deactivate
+ unset -f pydoc
+ '[' -z _ ']'
+ PATH=/home/geonatureadmin/geonature/backend/venv/bin:/home/geonatureadmin/.nvm/versions/node/v8.1.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/geonatureadmin/.local/bin:/home/geonatureadmin/bin
+ export PATH
+ unset _OLD_VIRTUAL_PATH
+ '[' -z '' ']'
+ '[' -n /bin/bash ']'
+ hash -r
+ '[' -z _ ']'
+ PS1=
+ export PS1
+ unset _OLD_VIRTUAL_PS1
+ unset VIRTUAL_ENV
+ '[' '!' '' = nondestructive ']'
+ unset -f deactivate

````

**Comment by TheoLechemia** [comment]
On peux continuer par mail pour ne pas polluer toute la liste de diffusion. On fera un recap ici quand ça marchera:
theo.lechemia at ecrins-parcnational.fr

**Comment by patricklbs** [comment]
@TheoLechemia Ok

**Comment by patricklbs** [comment]
Enfin !! 

![image](https://user-images.githubusercontent.com/1314444/56232808-e1fcce80-6081-11e9-9406-78e6179d5cfa.png)

Je vous ferez un retour une fois que j'aurais consolidé l'installation et la configuration. Trop content de pouvoir vous aider sur CentOS J'ai beaucoup appris en faisant l'installation alors merci !!  :)

**Comment by patricklbs** [comment]
Voilà Geonature tourne super bien sur CentOS 7 :)

![image](https://user-images.githubusercontent.com/1314444/56372040-860b8480-61fe-11e9-90aa-09bac5430c46.png)



![image](https://user-images.githubusercontent.com/1314444/56372109-a76c7080-61fe-11e9-84db-abd8db3aea29.png)



![image](https://user-images.githubusercontent.com/1314444/56372665-b69fee00-61ff-11e9-8243-5914e759ed73.png)




Prochaines étapes vous fournir une doc d'install et je prendrai du temps pour faire un script d'installation global.

Merci @TheoLechemia  ! 

Bonne continuation et bravo !! Bien content d'apporter ma petite contribution à ce beau projet qui allie l'informatique et la nature deux de mes passions :)


Patrick.

**Comment by camillemonchicourt** [comment]
Super !

**Comment by laurentm29** [comment]
Bonjour,
Je souhaiterais installé Géonature sur Centos. Serait-il possible d'avoir votre script d'installation et votre documentation ?
Merci,
Laurent

**Comment by patricklbs** [comment]
Je suis en Espagne en ce moment j'ai eu énormément de projets mais je vais
m'y atteler 😆

A bientôt.

Patrick.

Le lun. 30 sept. 2019 à 09:46, laurentm29 <notifications@github.com> a
écrit :

**Comment by patricklbs** [comment]
> 
> 
> Bonjour,
> Je souhaiterais installé Géonature sur Centos. Serait-il possible d'avoir votre script d'installation et votre documentation ?
> Merci,
> Laurent

Laurent,

Voici la mop d'installation en attendant que je finalise le script :

https://informaddict.ddns.net/doku.php?id=installation_finale#dokuwiki__top

Il y a deux modifications à apporter au fichier  install_apps.sh c'est le chemin de conf de supervisor 

/etc/supervisord.d 
et mettre dans /etc/supervisord.conf 

vi /etc/supervisord.conf
 
[include]
+files = supervisord.d/*.conf
-files = supervisord.d/*.ini

**Comment by laurentm29** [comment]
Merci Patrick pour ces informations qui m'ont permis d'avancer. Je bloque maintenant sur la configuration d'apache. Le répertoire "sites-available"  n'existe pas sous Centos et la commande a2ensite n'existe pas, est-il possible d'avoir vos scripts de configuration d'apache ?
Merci, Laurent

**Comment by patricklbs** [comment]
> 
> 
> Merci Patrick pour ces informations qui m'ont permis d'avancer. Je bloque maintenant sur la configuration d'apache. Le répertoire "sites-available" n'existe pas sous Centos et la commande a2ensite n'existe pas, est-il possible d'avoir vos scripts de configuration d'apache ?
> Merci, Laurent

Je t'en prie, désolé pour le temps de réponse. J'ai rajouté la conf Apache sur mon wiki.

Il faut que les noms de domaine répondent, moi je préfère passer par des domaine,  sous domaine plutôt que pas des url avec context path càd 

http://geonature.mrs/geonature c'est pas joli et pas correct.

si tu utilises un fqdn avec sous domaine il faut bien vérifier que le 

``/home/vgn/geonature/config/geonature_config.toml ``

soit bien renseigné, et refaire 

```
source backend/venv/bin/activate
geonature update_configuration
```

> 
La conf apache pour geonature 

```
#Configuration GeoNature sur sous-domaine
    <VirtualHost *:80>
            ServerName geonature.mrs
            DocumentRoot /home/geonature/frontend/dist
 
            <Directory /home/geonature/frontend/dist>
                    Require all granted
            </Directory>
 
            <Location /api>
                    ProxyPass http://127.0.0.1:8000
                    ProxyPassReverse  http://127.0.0.1:8000
            </Location>
    </VirtualHost>
# Fin de configuration de GeoNature
```
