### ISSUE TITLE
Dysfonctionnement de l'export ShapeFile avec des multipoint / multipolygon

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#786]
Les multipoint, sauf erreur, ne sont pas reconnus dans les formats shp. 

J'ai eu sur mon instance aujourd'hui un retour d'utilisatrice à cause de cette erreur d'exports, que j'ai pu retrouver dans les logs. Les données ont été importées en utilisant la doc , à partir de fichiers shape via qgis. Et je me suis trouvé sans le savoir avec des multipoints au lieu de points. 

Pas dur à régler, faut il une simple correction de la doc d'import? Est-ce pertinent dans le cas de vrais multpoints (dans mon cas j'avais des points simples reconnus comme multipoint sans savoir pourquoi, j'ai réglé le soucis avec st_dump). Ou est-ce que l'appli elle même peut identifier ces cas et les transformer ? Ou est-ce qu'il y a un moyen de le faire passer dans des formats shape ? Je pose ça là... pour voir si des experts en géomatiques pourront éclairer ma lanterne :)

**Comment by camillemonchicourt** [comment]
Les multipoints fonctionnent en SHP normalement et sont aussi censés fonctionner dans GeoNature

**Comment by DonovanMaillard** [comment]
Censés ;) 

Dans mon cas, l'export csv etait ok ainsi que le geojson. Mais pour le shp, le log était le suivant : 


`[2019-11-06 16:45:35 +0100] [6077] [ERROR] Error handling request /synthese/export_observations?export_format=shapefile
Traceback (most recent call last):
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pole-gnadmin/geonature/backend/server.py", line 38, in __call__
    return self.app(environ, start_response)
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pole-gnadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 95, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/pole-gnadmin/geonature/backend/geonature/core/gn_synthese/routes.py", line 387, in export_observations_web
    file_name=file_name,
  File "/home/pole-gnadmin/geonature/backend/geonature/utils/utilssqlalchemy.py", line 205, in as_shape
    file_name=file_name,
  File "/home/pole-gnadmin/geonature/backend/geonature/utils/utilsgeometry.py", line 257, in create_shapes_generic
    FionaShapeService.create_features_generic(view, data, geom_col, geojson_col)
  File "/home/pole-gnadmin/geonature/backend/geonature/utils/utilsgeometry.py", line 191, in create_features_generic
    cls.polyline_shape.write(feature)
  File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/fiona/collection.py", line 341, in write
    self.writerecords([record])
File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/fiona/collection.py", line 335, in writerecords
    self.session.writerecs(records, self)
  File "fiona/ogrext.pyx", line 1065, in fiona.ogrext.WritingSession.writerecs
ValueError: Record's geometry type does not match collection schema's geometry type: 'MultiPoint' != 'LineString'
CPLE_NotSupported in b"Normalized/laundered field name: 'Id_producteur' to 'Id_product'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Jeu_donnees' to 'Jeu_donnee'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Observateurs' to 'Observateu'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Determinateur' to 'Determinat'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Methode_obs' to 'Methode_ob'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Com_occurrence' to 'Com_occurr'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Integr_sinp' to 'Integr_sin'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Id_producteur' to 'Id_product'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Jeu_donnees' to 'Jeu_donnee'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Observateurs' to 'Observateu'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Determinateur' to 'Determinat'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Methode_obs' to 'Methode_ob'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Com_occurrence' to 'Com_occurr'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Integr_sinp' to 'Integr_sin'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Id_producteur' to 'Id_product'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Jeu_donnees' to 'Jeu_donnee'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Observateurs' to 'Observateu'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Determinateur' to 'Determinat'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Methode_obs' to 'Methode_ob'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Com_occurrence' to 'Com_occurr'"
CPLE_NotSupported in b"Normalized/laundered field name: 'Integr_sinp' to 'Integr_sin'"
`
