### ISSUE TITLE
Bug: Installation module python markupSafe

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#881]
Sur une Ubuntu 18.04.4 LTS fraichement installé

Le problème vient de setuptools et est corrigé avec la version 1.1 de markupsafe (https://github.com/pallets/markupsafe/issues/57)

```
Collecting markupsafe==1.0
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/admin_pnc/dev/GeoNature/backend/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-shyq_34b/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-shyq_34b/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-shyq_34b/markupsafe/pip-egg-info
         cwd: /tmp/pip-install-shyq_34b/markupsafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-shyq_34b/markupsafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by camillemonchicourt** [comment]
En installant quelle version de GeoNature ?

**Comment by amandine-sahl** [comment]
La 2.3.2.
Mais dans la branch develop markupsafe est toujours en version 1.0
