### ISSUE TITLE
[2.3.2] Erreur à l'inscription / Récupération de mdp 

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#944]
Bonjour,

J'ai suivi [la doc pour configurer la création de compte](http://docs.geonature.fr/admin-manual.html#creation-de-compte), et aucun problème avec GeoNature 2.3.1 (création de compte et récupération de mot de passe).

Par contre, avec GN 2.3.2, ça ne fonctionne plus, et ça ressemble _a priori_ à cette erreur : https://github.com/PnX-SI/UsersHub-authentification-module/issues/29

Voilà les log : 

```
Exception on /users/inscription [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd8e51484a8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gntest.marie-filipe.fr', port=443): Max retries exceeded with url: /api/pypn/register/post_usershub/create_temp_user (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd8e51484a8>: Failed to establish a new connection: [Errno -2] Name or service not known')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/users/routes.py", line 285, in inscription
    json=data,
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='gntest.marie-filipe.fr', port=443): Max retries exceeded with url: /api/pypn/register/post_usershub/create_temp_user (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd8e51484a8>: Failed to establish a new connection: [Errno -2] Name or service not known')))
```

Problème réglé en commentant les 2 lignes sur les proxy dans le fichier geonature/backend/gunicorn_start.sh : 

```
#export HTTP_PROXY="'$proxy_http'"
#export HTTPS_PROXY="'$proxy_https'"
```

Edit : pour préciser un peu, le problème apparaît lors d'une installation directe de la v 2.3.2, je n'ai pas testé avec une montée en version de la 2.3.1 vers la 2.3.2 (j'ai testé sur une instance en 2.3.1 puis sur une instance en 2.3.2, chacune installée de façon indépendante).

**Comment by TheoLechemia** [comment]
C'est identifié oui, mais ça n'avais pas été corrigé dans le .sample, du coup l'erreur traîne.
merci

**Comment by camillemonchicourt** [comment]
Corrigé : https://github.com/PnX-SI/GeoNature/commit/2ee5c108714eb4804bab71c217f504409ea7e68b

**Comment by camillemonchicourt** [comment]
Corrigé dans 2.4.0.
