### ISSUE TITLE
Installation globale Geonature 2.4.1

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/GeoNature#970]
Bonjour,
J'ai installé l'application Geonature 2.4.1 sur un serveur OVH debian 9 et suivi les instructions d'installation. L'installation est allé jusqu'au bout. Cependant j'ai testé les applications en l'état sur le serveur est seule l'application taxhub  1.7.2 fonctionne.
1) Geonature 4.2.1 ne fonctionne pas et renvoie une erreur sur l'url :
Dans le log apache on trouve cet erreur (j'ai vu que je n'étais pas le seul mais je ne sais pas quoi faire ....) 
[Wed Jul 08 14:52:55.019471 2020] [authz_core:error] [pid 17696:tid 140614897211136] [client 176.130.163.185:55940] AH01630: client denied by server configuration: /home/geonatureadmin/geonature/frontend/dist
J'ai regardé : le répertoire ./frontend/dist n'existe pas ! Comme nous avons un autre serveur qui fonctionne, j'ai constaté que ce répertoire sont les fichiers javascript de l'application. 
J'ai tenté de faire un npm run build mais j'obtiens cette erreur.
Found '/home/geonatureadmin/geonature/frontend/.nvmrc' with version <v10.15.3>
Now using node v10.15.3 (npm v6.4.1)
ENOENT: no such file or directory, stat '/home/geonatureadmin/geonature/frontend/src/tsconfig.app.json'
Error: ENOENT: no such file or directory, stat '/home/geonatureadmin/geonature/frontend/src/tsconfig.app.json'
    at Object.statSync (fs.js:850:3)
    at AngularCompilerPlugin._setupOptions (/home/geonatureadmin/geonature/frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:85:16)
    at new AngularCompilerPlugin (/home/geonatureadmin/geonature/frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:53:14)
    at _createAotPlugin (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js:37:12)
    at Object.getNonAotConfig (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js:43:19)
    at BrowserBuilder.buildWebpackConfig (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/src/browser/index.js:89:37)
    at MergeMapSubscriber.rxjs_1.of.pipe.operators_1.concatMap [as project] (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/src/browser/index.js:37:38)
    at MergeMapSubscriber._tryNext (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SafeSubscriber.__tryOrUnsub (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:209:16)
    at SafeSubscriber.next (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:147:22)
    at Subscriber._next (/home/geonatureadmin/geonature/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:90:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geonature@0.0.0 build: `. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geonature@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Par ailleurs, j'avais contaté que les APIS pour Geonture était aussi en erreur. J'ai relancé maintenant cela tourne.
Pouvez-vous m'aider à faire fonctionner l'application sur ce tout nouveau serveur ? 

2) l'application userHub 2.1.2 ne se lance pas non plus dans l'explorateur.
Je tape l'adresse http://151.80.57.214/usershub et cela renvoie cet url : 
http://localhost151.80.57.214/usershub/151.80.57.214/usershub/users/list
Il n'y a pas d'erreur dans les logs.
Est ce un problème de configuration. Pourtant tout semble correct côté configuration Apache.

Cistude Nature

**Comment by TheoLechemia** [comment]
Bonjour,
il faudrait les logs d'install complet et le install_all.ini  pour comprendre ce qu'il s'est passé.
Pour usershub, à prirori c'est juste le paramètre URL_APPLICATION qui n'est pas bien rempli.

**Comment by christianbieche** [comment]
Voilà le log et le fichier de paramètre. Dans se log effectivement il y a quelques erreurs que je ne sais pas interprété.
Pour userHub, ce paramètre se trouve où ? que doit-il contenir ? 
[install_all.log](https://github.com/PnX-SI/GeoNature/files/4891967/install_all.log)
[OVH2.zip](https://github.com/PnX-SI/GeoNature/files/4891976/OVH2.zip)

**Comment by TheoLechemia** [comment]
Il se trouve dans "config/config.py" du répertoire usershub, et il doit contenir... l'url de l'application. Soit <VOTRE_IP>/usershub

**Comment by TheoLechemia** [comment]
L'erreur vient du paramètre `my_url=151.80.57.214/`, il faut mettre un http devant: `my_url=http://151.80.57.214/`.
Vous relancer l'installation en réinitialisant le serveur

**Comment by christianbieche** [comment]
cad relancer l'application en réinitialisant le serveur ? dois-je recréer mon serveur OVH et refaire l'installation depuis le début ou puis je relancer le script d'install après correction avec le paramètre drop_geonaturedb=true simplement ?

**Comment by christianbieche** [comment]
bonjour,
J'ai relancé le script d'installation en modifiant l'url et en demandant la récreation de la base geonature. 
Maintenant taxhub se lance ainsi qu'userhub, mais j'ai toujours le problème de Geonature qui ne crée pas le répertoire dist à l'install et donc cela ne fonctionne pas.
Cistude nature

**Comment by TheoLechemia** [comment]
`cad relancer l'application en réinitialisant le serveur ? dois-je recréer mon serveur OVH et refaire l'installation depuis le début ou puis je relancer le script d'install après correction avec le paramètre drop_geonaturedb=true simplement ?`
Oui c'est aussi possible comme ça. Il faut bien supprimer les répertoire geonature, taxhub et usershub puis faire un `sudo service postgresql restart` avant de relancer le script

**Comment by christianbieche** [comment]
Merci bien, j'ai effectivement relancé l'installation après suppression des répertoires et restart postgresql et toutes les applications fonctionnent.
Il faut donc bien mettre une url de la forme : http:// avec soit le nom DNS ou l'adresse ip du serveur suivi de /
C'est noté pour une prochaine fois merci.

Du coup pour la mises à jour futures des applications. Peut-on utiliser la même technique ? on met de côté les répertoires et on fait une install_all en mettant le paramètre du fichier .ini drop_geonaturedb=false pour ne pas effacer ces données.

**Comment by camillemonchicourt** [comment]
OK pour l'installation.
Pour les mises à jour, la procédure est différente et détaillée dans la documentation de GeoNature : http://docs.geonature.fr/installation-standalone.html#mise-a-jour-de-l-application
Il peut y avoir aussi des mises à jour de TaxHub et UsersHub à faire en parallèle (voir leur doc respective).
