### ISSUE TITLE
fatal error sur lancement geonature

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/GeoNature#983]
Bonjour,
Aprés installation de geonature, j'ai configuré mon système (debian 9 sous OVH) pour un accès en HTTPS en utilisant un nom de domaine.
Cela a fonctionné  pendant un moment mais cela ne fonctionne plus. UsersHub et Taxhub fonctionne mais impossible de relancer Geonature j'ai une erreur visiblement dans les bibliothèque : 
un extrait du log de geonature. 
Il y a une erreur : toml.TomlDecodeError: Found invalid character in key name: '#'

Pouvez-vous me dire ce que je dois faire pour démarrer geonature ?
Cordialement,
christian Bièche
Cistude Nature

File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/util.py", line 376, in import_app
    __import__(module)
  File "/home/geonatureadmin/geonature/backend/wsgi.py", line 8, in <module>
    from geonature.utils.env import load_config, get_config_file_path
  File "/home/geonatureadmin/geonature/backend/geonature/__init__.py", line 7, in <module>
    conf = load_config(DEFAULT_CONFIG_FILE)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/env.py", line 133, in load_config
    str(get_config_file_path(config_file)), GnPySchemaConf
  File "/home/geonatureadmin/geonature/backend/geonature/utils/utilstoml.py", line 13, in load_and_validate_toml
    toml_config = load_toml(toml_file)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/utilstoml.py", line 27, in load_toml
    toml_config = toml.load(str(toml_file))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/toml.py", line 88, in load
    return loads(ffile.read(), _dict)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/toml.py", line 176, in loads
    item + "'. Try quoting the key name.")
toml.TomlDecodeError: Found invalid character in key name: '#'. Try quoting the key name.
[2020-07-22 09:27:24 +0000] [5339] [INFO] Worker exiting (pid: 5339)
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by amandine-sahl** [comment]
Bonjour, 

A priori le fichier de configuration `config/geonature_config.toml` n'est pas valide.
Pour le valider vous pouvez utiliser l'utilitaire suivant : https://www.toml-lint.com/
